# $Id: Makefile 2591 2011-08-13 22:12:23Z kate $

.include "Makefile.inc"


ENVFILE+=	default

ENVFILE+=	tcc_diag

ENVCOMMON+=	machines/common/env
ENVCOMMON+=	machines/${OSFAM}/common/env
ENVCOMMON+=	machines/${OSFAM}/mips/env/common

.include <tendra.env.mk>

