# $TenDRA$


PROG=  trans

SRCS= sparcdiags.c


# installers/sparc
+.include "${.CURDIR}/../Makefile.inc"

# installers/
+.include "${.CURDIR}/../../Makefile.inc"

+.include "${.CURDIR}/../../../../mk/base/tendra.prog.mk"

