# $Id$

NAME=disp.1
SOURCE=disp.1.xml
PROJECT_NAME=disp
PROJECT_URL=http://docs.tendra.org/
RESOURCES=../style/docbook.css ../style/common.css
CSSFILE=docbook.css
XHTMLSTYLE=../xsl/tendra-docbook-chunked.xsl
XHTMLSTYLE_SINGLE=../xsl/tendra-docbook-single.xsl

include ../doctools/Mk/man.mk
include ../doctools/Mk/docbook.mk

