# $Id$

.include "Makefile.inc"


ENVFILE+=	Goption
ENVFILE+=	K-P5
ENVFILE+=	K-frame
ENVFILE+=	K-i386
ENVFILE+=	K-i486
ENVFILE+=	K-noframe

ENVFILE+=	Xa
ENVFILE+=	Xc
ENVFILE+=	Xp
ENVFILE+=	Xs
ENVFILE+=	Xt
ENVFILE+=	Xw

ENVFILE+=	Z-p
ENVFILE+=	Z-p1
ENVFILE+=	Z-p2
ENVFILE+=	Z-p4

ENVFILE+=	tcc_diag
ENVFILE+=	tcc_prof

ENVEXTRA+=	default.extra

ENVCOMMON+=	machines/common/env
ENVCOMMON+=	machines/${OSFAM}/common/env

.include <tendra.env.mk>

