# $Id$

.include "Makefile.inc"


ENVFILE+=	default

ENVFILE+=	Goption

ENVCOMMON+=	machines/common/env
ENVCOMMON+=	machines/common/arch/${BLDARCH}/env
ENVCOMMON+=	machines/${OSFAM}/common/env

.include <tendra.env.mk>

