# $Id$

.include "Makefile.inc"


CCOPTS+=	-I ../../common/construct
CCOPTS+=	-I ../../common/obj_c
CCOPTS+=	-I ../../common/output
CCOPTS+=	-I ../../common/parse
CCOPTS+=	-I ../../common/utility
CCOPTS+=	-I ../../common

SRCS+=	syntax1.c
SRCS+=	syntax2.c
SRCS+=	syntax3.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

