# $Id$

.include "Makefile.inc"


DOC=       	${.CURDIR:T}
DOC_PREFIX=	${.CURDIR:H:T}
DOC_DPADD+= \
	api.xml          \
	basicmapping.xml \
	lpi.xml          \
	namingscheme.xml \
	preface.xml      \
	targetdep.xml    \
	tdfinterface.xml

.include <tendra.doc.mk>
