/*
 * Copyright 2011, The TenDRA Project.
 * Copyright 1997, United Kingdom Secretary of State for Defence.
 *
 * See doc/copyright/ for the full copyright terms.
 */


/*
    DISK READING AND WRITING SUBALGEBRA

    This algebra describes the subset of the complete algebra used in
    the disk reading and writing routines.
*/

ALGEBRA disk (1.1):

IMPORT calculus::TYPE ;

disk_int = int ;
disk_string = string ;
disk_list_ptr_type = LIST PTR TYPE ;
