/*
 * Copyright 2011, The TenDRA Project.
 * Copyright 1997, United Kingdom Secretary of State for Defence.
 *
 * See doc/copyright/ for the full copyright terms.
 */

/*
 *  AUTOMATICALLY GENERATED BY lexi VERSION 1.2
 */


/* KEYWORDS */

MAKE_KEYWORD("boundaries", lex_boundaries);
MAKE_KEYWORD("break", lex_break);
MAKE_KEYWORD("construct_name", lex_construct_Hname);
MAKE_KEYWORD("constructs", lex_constructs);
MAKE_KEYWORD("edge_constructor", lex_edge_Hconstructor);
MAKE_KEYWORD("edge_sort", lex_edge_Hsort);
MAKE_KEYWORD("encoding", lex_encoding);
MAKE_KEYWORD("encoding_bits", lex_encoding_Hbits);
MAKE_KEYWORD("entity_identifier", lex_entity_Hidentifier);
MAKE_KEYWORD("entity_sort", lex_entity_Hsort);
MAKE_KEYWORD("graph_edges", lex_graph_Hedges);
MAKE_KEYWORD("has_extension", lex_has_Hextension);
MAKE_KEYWORD("kinds_of_unit", lex_kinds_Hof_Hunit);
MAKE_KEYWORD("linkable_entities", lex_linkable_Hentities);
MAKE_KEYWORD("lists", lex_lists);
MAKE_KEYWORD("major_version", lex_major_Hversion);
MAKE_KEYWORD("minor_version", lex_minor_Hversion);
MAKE_KEYWORD("options", lex_options);
MAKE_KEYWORD("parameter_sorts", lex_parameter_Hsorts);
MAKE_KEYWORD("result_sort", lex_result_Hsort);
MAKE_KEYWORD("slists", lex_slists);
MAKE_KEYWORD("sortid", lex_sortid);
MAKE_KEYWORD("sorts", lex_sorts);
MAKE_KEYWORD("unit_elements", lex_unit_Helements);
MAKE_KEYWORD("unit_identifier", lex_unit_Hidentifier);
