# $Id$

NAME = porting
SECTION = papers
THEMEFILENAME = website
DOCTOOLS_BASE = ../../build

XHTMLIMAGES = eg_scheme.png tdf_scheme.png token_args.png \
	tdf_link.png token.png trad_scheme.png

include $(DOCTOOLS_BASE)/docs.mk

