# $TenDRA$

SRCDIRS+=	680x0/common

# installers/680x0/common
SRCS+=	68k_globals.c codec.c coder.c codex.c evaluate.c general_proc.c glopt.c \
	inliner.c input.c instr.c mach_ins.c mach_op.c ops_float.c ops_int.c \
	ops_logic.c ops_misc.c output.c peephole.c scan2.c spec_tok.c \
	special_exps.c stab_types.c tests.c trans.c utility.c weights.c where.c \
	xdb_basics.c xdb_output.c xdb_types.c
