# $Id$

.include "Makefile.inc"


# XXX: hack
ENVCOMMON=

ENVFILE+=	base
ENVFILE+=	default
#ENVFILE+=	system
#ENVFILE+=	system+
#ENVFILE+=	building
ENVFILE+=	Versions
ENVFILE+=	status

#ENVFILE+=	c
#ENVFILE+=	c++
#ENVFILE+=	iso
#ENVFILE+=	ansi

ENVFILE+=	Xa
ENVFILE+=	Xc
ENVFILE+=	Xp
ENVFILE+=	Xs
ENVFILE+=	Xt
ENVFILE+=	Xw
ENVFILE+=	Xsystem

ENVFILE+=	pl_tdf
ENVFILE+=	tdp
ENVFILE+=	tnc
ENVFILE+=	tsimp
ENVFILE+=	makelib

ENVFILE+=	common
ENVFILE+=	16bit
ENVFILE+=	32bit

ENVFILE+=	compact
ENVFILE+=	longlong
ENVFILE+=	tcc_pp
ENVFILE+=	tcc_prof
ENVFILE+=	tcc_time
ENVFILE+=	wsl

.include <tendra.env.mk>

