# $TenDRA$
#
#

DOC_PREFIX?=../../

SUBDIR=		calculus disp lexi make_tdf mkerr pl sid tcc tchk tcpplus \
		tdfc2 tld tnc tspec

# installer manpages
SUBDIR+=	trans


.include "${DOC_PREFIX}/share/mk/doc.project.mk"
