# $TenDRA$

.PATH : ${.OBJDIR}/../../iso.api

# Defs for lib/apis/diag
.include "${.CURDIR}/../Makefile.inc"

# Defs for lib/apis
.include "${.CURDIR}/../../Makefile.inc"

# Source for the api itself
.include "${.CURDIR}/../../iso/Makefile.inc"

.include "${.CURDIR}/../../../../../mk/base/tendra.prog.mk"
