# $Id: Makefile 2489 2010-12-28 20:45:16Z kate $

.include "Makefile.inc"

.include <tendra.base.mk>


ENVFILE+=	default

ENVCOMMON+=	machines/common/env
ENVCOMMON+=	arch/${BLDARCH}/env
ENVCOMMON+=	machines/${OSFAM}/common/env

.include <tendra.env.mk>

