# $Id: Makefile 2489 2010-12-28 20:45:16Z kate $

.include "Makefile.inc"


ENVEXTRA+=	default.extra

ENVCOMMON+=	machines/common/env
ENVCOMMON+=	machines/${OSFAM}/common/env

.include <tendra.env.mk>

