# $Id$

MAN=	lexi.1
DOC=	lexi.1

.if exists(../share)
# building standalone
# TODO override STYLEDIR here
.include "../share/doc.docbook.mk"
.else
# building within tendra-doc
.include "../../../share/doc.docbook.mk"
.endif

