#!/bin/sh

BASE=/u/g/release/Source
UTIL=${BASE}/src/utilities
SRC=${UTIL}/calculus

make_mf\
    +A BASE=${BASE}\
    +A UTIL=${UTIL}\
    +A SRC=${SRC}\
    +A SRC2=${SRC}/obj_c\
    +A SRC2A=${SRC}/obj_tok\
    +A SRCX=${UTIL}/shared\
    +W ...\
    +V 'EXTRA=auto'\
    -o .../calculus\
    -Yansi -Xs\
    -I ${SRC}\
    -I ${SRC}/obj_c\
    -I ${UTIL}/shared\
    ${SRC}/*.c\
    ${SRC}/obj_c/*.c\
    ${UTIL}/shared/*.c\
    > Makefile

make_mf\
    +fcheck.ini\
    +A BASE=${BASE}\
    +A UTIL=${UTIL}\
    +A SRC=${SRC}\
    +A SRC2=${SRC}/obj_c\
    +A SRC2A=${SRC}/obj_tok\
    +A SRCX=${UTIL}/shared\
    +W ...\
    -o .../calculus.k\
    -Yansi -Xs\
    -I ${SRC}\
    -I ${SRC}/obj_tok\
    -I ${UTIL}/shared\
    ${SRC}/*.c\
    ${UTIL}/shared/*.c\
    > Makefile.chk

cat >> Makefile << EOF

CALCULUS=calculus
LEXI=lexi
SID=sid
SIDOPTS=-l ossg-c -s no-lines

SID_OUT=\${SRC}/syntax.c \${SRC}/syntax.h
C_OUT=\${SRC2}/calculus.h \${SRC2}/type_ops.h
TOK_OUT=\${SRC2A}/calculus.h \${SRC2A}/type_ops.h
DISK_OUT=\${SRC}/read_def.h \${SRC}/write_def.h \${SRC}/print_def.h
LEXI_OUT=\${SRC}/lexer.h \${SRC}/keyword.h

auto : \${SID_OUT} \${C_OUT} \${TOK_OUT} \${DISK_OUT} \${LEXI_OUT}

\${SRC}/syntax.c : \${SRC}/syntax.sid \${SRC}/syntax.act
	@\${REMOVE} \${SID_OUT}
	\${SID} \${SIDOPTS} \${SRC}/syntax.sid \${SRC}/syntax.act \${SID_OUT}

\${SRC2}/calculus.h : \${SRC}/calculus.alg
	@\${REMOVE} \${SRC2}/*.h
	\${CALCULUS} -a -x \${SRC}/calculus.alg \${SRC2}

\${SRC2A}/calculus.h : \${SRC}/calculus.alg
	@\${REMOVE} \${SRC2A}/*.h
	\${CALCULUS} -a -x -t \${SRC}/calculus.alg \${SRC2A}

\${SRC}/read_def.h : \${SRC}/calculus.alg \${SRC}/disk.alg
	@\${REMOVE} \${SRC}/read_def.h \${SRC}/write_def.h
	\${CALCULUS} -a -x -d \${SRC}/calculus.alg \${SRC}/disk.alg \${SRC}

\${SRC}/print_def.h : \${SRC}/calculus.alg
	@\${REMOVE} \${SRC}/print_def.h
	\${CALCULUS} -a -x -p \${SRC}/calculus.alg \${SRC}

\${SRC}/lexer.h : \${SRC}/lexer.lxi
	@\${REMOVE} \${SRC}/lexer.h
	\${LEXI} \${SRC}/lexer.lxi \${SRC}/lexer.h

\${SRC}/keyword.h : \${SRC}/lexer.lxi
	@\${REMOVE} \${SRC}/keyword.h
	\${LEXI} -k \${SRC}/lexer.lxi \${SRC}/keyword.h

auto_clobber :
	\${REMOVE} \${SID_OUT}
	\${REMOVE} \${SRC2}/*.h
	\${REMOVE} \${SRC2A}/*.h
	\${REMOVE} \${DISK_OUT}
	\${REMOVE} \${LEXI_OUT}
EOF
