# $TenDRA$

PROG=	trans

# installers/80x86/sco
SRCS=	assembler.c cv_fns.c cv_outtype.c machine.c

# installers/80x86
.include "${.CURDIR}/../Makefile.inc"

# installers/
.include "${.CURDIR}/../../Makefile.inc"

.include "${.CURDIR}/../../../../mk/base/tendra.prog.mk"
