# $Id$

.include "Makefile.inc"


CCOPTS+=	-I ../../common/construct
CCOPTS+=	-I ../../common/diag
CCOPTS+=	-I ../../common/dwarf2
CCOPTS+=	-I ../../common/linkinfo
CCOPTS+=	-I ../../common/reader
CCOPTS+=	-I ../../common/refactor

SRCS+=	codehere.c
SRCS+=	comment.c
SRCS+=	dw2_extra.c
SRCS+=	eval.c
SRCS+=	getregs.c
SRCS+=	glopt.c
SRCS+=	guard.c
SRCS+=	inlinechoice.c
SRCS+=	inst_fmt.c
SRCS+=	is_worth.c
SRCS+=	labels.c
SRCS+=	locate.c
SRCS+=	machine.c
SRCS+=	machine_toks.c
SRCS+=	main.c
SRCS+=	makecode.c
SRCS+=	move.c
SRCS+=	muldvrem.c
SRCS+=	needscan.c
SRCS+=	oprators.c
SRCS+=	proc.c
SRCS+=	regable.c
SRCS+=	regalloc.c
SRCS+=	regexps.c
SRCS+=	sparcins.c
SRCS+=	spec_tok.c
SRCS+=	special.c
SRCS+=	tempdecs.c
SRCS+=	translat.c
SRCS+=	weights.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

