# $Id$

.include "Makefile.inc"


CCOPTS+=	-I ../../common/obj_c
CCOPTS+=	-I ../../common/output
CCOPTS+=	-I ../../common/parse
CCOPTS+=	-I ../../common
CCOPTS+=	-I ../utility

SRCS+=	access.c
SRCS+=	allocate.c
SRCS+=	assign.c
SRCS+=	basetype.c
SRCS+=	cast.c
SRCS+=	check.c
SRCS+=	chktype.c
SRCS+=	class.c
SRCS+=	construct.c
SRCS+=	convert.c
SRCS+=	copy.c
SRCS+=	declare.c
SRCS+=	derive.c
SRCS+=	destroy.c
SRCS+=	exception.c
SRCS+=	expression.c
SRCS+=	function.c
SRCS+=	identifier.c
SRCS+=	initialise.c
SRCS+=	instance.c
SRCS+=	inttype.c
SRCS+=	label.c
SRCS+=	member.c
SRCS+=	merge.c
SRCS+=	namespace.c
SRCS+=	operator.c
SRCS+=	overload.c
SRCS+=	printf.c
SRCS+=	quality.c
SRCS+=	redeclare.c
SRCS+=	rewrite.c
SRCS+=	statement.c
SRCS+=	template.c
SRCS+=	tokdef.c
SRCS+=	token.c
SRCS+=	typeid.c
SRCS+=	variable.c
SRCS+=	virtual.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

