# $Id$

NAME=calculus.1
SOURCE=calculus.1.xml
PROJECT_NAME=calculus
PROJECT_URL=http://docs.tendra.org/
RESOURCES=../style/docbook.css ../style/common.css
CSSFILE=docbook.css
XHTMLSTYLE=../xsl/tendra-docbook-chunked.xsl
XHTMLSTYLE_SINGLE=../xsl/tendra-docbook-single.xsl

TEXFILE=docbook.tex
TEXINPUTS=../style/tex

include ../doctools/Mk/man.mk
include ../doctools/Mk/docbook.mk

