# $TenDRA$

# Directories where the api library makefiles are. (respectivly)
SUBDIR=	ansi bsd_extn gcc posix1 posix2 svid3 unix95 xpg4

#These are broken and need to be checked
#SUBDIR+= posix xpg3

.include "../../../../mk/base/tendra.subdir.mk"
