# $Id$

.include "Makefile.inc"


CCOPTS+=	-I ..
CCOPTS+=	-I .

SRCS+=	aldefs.c
SRCS+=	complex_eq.c
SRCS+=	exp.c
SRCS+=	f64.c
SRCS+=	flpt.c
SRCS+=	flpt_fns.c
SRCS+=	install_fns.c
SRCS+=	installglob.c
SRCS+=	label_ops.c
SRCS+=	me_fns.c
SRCS+=	misc_c.c
SRCS+=	machine.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

