# $Id$

.include "Makefile.inc"


CCOPTS+=	-I ..
CCOPTS+=	-I .

SRCS+=	callop.c
SRCS+=	aldefs.c
SRCS+=	exp.c
SRCS+=	install_fns.c
SRCS+=	installglob.c
SRCS+=	label_ops.c
SRCS+=	me_fns.c
SRCS+=	machine.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

