# $Id: Makefile 2308 2010-02-11 02:08:11Z kate $

.include "Makefile.inc"


MACHTOK_DEP   	= dep_toks.tpl
MACHTOK_MAP   	= map_toks.tpl
MACHTOK_EXCEPT	= except_toks.tpl
MACHTOK_MODEL 	= ilp32.tpl

.include <tendra.machtok.mk>

