# $Id: Makefile 2308 2010-02-11 02:08:11Z kate $

.include "Makefile.inc"

.include <tendra.base.mk>
.include <tendra.makedefs.mk>


MACHTOK_MAP   	= map_toks.tpl
MACHTOK_EXCEPT	= ${BLDARCH}.tpl
MACHTOK_MODEL 	= ilp32.tpl
MACHTOK_FLOAT 	= ieee754-ext80.tpl
MACHTOK_INT   	= ${BLDARCH}.tpl

.include <tendra.machtok.mk>

