# $TenDRA$

SRCDIRS=        cpp/syntax common common/construct common/obj_templ  \
		common/output common/parse common/utility

PROG = tcpplus

# cpp/syntax
SRCS=   syntax1.c syntax2.c syntax3.c syntax4.c syntax5. syntax6.c \
        syntax7.c

.include "${.CURDIR}/../Makefile.inc"

.include "${.CURDIR}/../../../mk/base/tendra.prog.mk"
