# $TenDRA$

SRCDIRS+=	alpha/common

# installers/alpha/common
SRCS+=	alpha_ins.c alphadiags.c bstack.c code_here.c coder.c comp_eq_exp.c \
	cross.c dump_distr.c eval.c extern_adds.c fail.c file.c float.c \
	frames.c getregs.c glopt.c guard.c handle_sregs.c inlinechoice.c \
	inst_fmt.c is_worth.c labels.c locate.c machine.c machine_toks.c \
	makesymtab.c move.c oddtest.c operators.c out_ba.c pseudo.c regable.c \
	regalloc.c regexps.c scan.c spec.c spec_tok.c special.c symbol.c \
	symdiags.c syms.c tempdecs.c translate.c type_to_aux.c weights.c
