# $Id$

.include "Makefile.inc"


CCOPTS+=	-I ..
CCOPTS+=	-I .

SRCS+=	refactor.c
SRCS+=	refactor_id.c
SRCS+=	refactor_ext.c
SRCS+=	case_opt.c
SRCS+=	global_opt.c
SRCS+=	const.c
SRCS+=	foralls.c
SRCS+=	inline.c
SRCS+=	inl_norm.c
SRCS+=	unroll.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

