.\" Copyright (c) 2002-2004 The TenDRA Project <http://www.ten15.org/> 
.\" All rights reserved. 
.\"  
.\" Redistribution and use in source and binary forms, with or without 
.\" modification, are permitted provided that the following conditions 
.\" are met: 
.\" 1. Redistributions of source code must retain the above copyright 
.\"    notice, this list of conditions and the following disclaimer. 
.\" 2. Redistributions in binary form must reproduce the above copyright 
.\"    notice, this list of conditions and the following disclaimer in the 
.\"    documentation and/or other materials provided with the distribution. 
.\"  
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND 
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE 
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS 
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY 
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF 
.\" SUCH DAMAGE. 
.\" 
.\" $TenDRA$
.\" 
.TH "trans386" "1" "Sat 07 Aug 2004, 18:35" "The TenDRA Project" "The TenDRA Project" 
.SH "NAME" 
.PP 
\fBtrans386\fP - Translator for 80386, 80486 and Pentium on SCO
.SH "SYNOPSIS"
.PP
\fBtrans386\fP [\fIoptions\fP] \fIinput-fileoutput-file\fP 
.SH "DESCRIPTION"
.PP
The code production portion of the TDF compiler is under the control of
a TDF translator, which translates a TDF capsule into an assembly source
file\&. There are separate TDF translators for each target architecture\&. This
manual page describes the installer for the 80x86 architecture\&.
.PP
The basic action of the TDF translator, \fBtrans386\fP, is
to translate a TDF capsule, \fIinput-file\fP, into
an assembly source file, \fIoutput-file\fP\&.
.PP
It is recommended that \fBtrans386\fP should not be
invoked directly, but via the user interface \fBtcc\fP\fB(1)\fP\&. The option
\fI-\fP\fIopt\fP can be
passed to \fBtrans386\fP by passing the option \fB-Wt,
-\fP\fIopt\fP to \fBtcc\fP\fB(1)\fP\&.
.SH "OPTIONS"
.IP "\fB-A\fP\fIswitch\fP" 5
This option determines whether \fBtrans386\fP should
inline calls to \fIalloca\fP\&. This is done by
default\&.
.IP "\fB-B\fP\fIswitch\fP" 5
This option determines whether \fBtrans386\fP should
report floating point constants which exceed their range\&. This is
always done by default\&. If this option is switched off such constants
are replaced by infinity\&.
.IP "\fB-C\fP\fIswitch\fP" 5
This option determines whether \fBtrans386\fP should
apply the "constants out of loops" optimisation\&. This optimisation is
performed by default\&.
.IP "\fB-D\fP\fIswitch\fP" 5
This option determines whether \fBtrans386\fP should
produce Position Independent Code (PIC)\&. This is not done by default\&.
This option is not supported on the SCO or FreeBSD platforms, and on
the Linux platform it is supported only for ELF binary format\&.
.IP "\fB-E\fP" 5
This option disables \fBtrans386\fP&39;s constant
overflow checks\&.
.IP "\fB-F\fP\fIswitch\fP" 5
This option determines whether \fBtrans386\fP should
apply the "strength reduction" optimisation\&. This optimisation is
performed by default\&.
.IP "\fB-G\fP" 5
To be documented\&.
.IP "\fB-H\fP" 5
This option causes \fBtrans386\fP to output
debugging information in its output file\&. This will only work if the
input TDF capsule contains debugging information\&. On the SCO platform
the format used by \fIdbxtra\fP and
\fIcodeview\fP is supported\&. On the SVR4\&.2
platform Dwarf 1 is supported, which is used by
\fIdebug\fP\&. On the Solaris, FreeBSD, and Linux
platforms, \fIstabs\fP is supported\&. The GNU debugger
\fIgdb\fP may be used on all platforms\&.
.IP "\fB-I\fP\fIswitch\fP" 5
This option determines whether \fBtrans386\fP should
apply the "inlining" optimisation\&. This optimisation is performed by
default\&.
.IP "\fB-K\fP\fIstr\fP" 5
Causes \fBtrans386\fP to optimise its code for
a particular processor model, determined by
\fIstr\fP\&. The available values of
\fIstr\fP are 3 for the 80386, 4 for the 80486
and 5 for the Pentium (the default)\&. So \fB-K3\fPmeans optimise for the 80386 etc\&.
.IP "\fB-M\fP\fIswitch\fP" 5
If this option is on, \fBtrans386\fP preserves
division by a floating point number rather than replacing it by
multiplication by the reciprocal of the number\&. While the latter
produces faster code, it may lead to rounding errors\&. By default,
division by constants is preserved\&.
.IP "\fB-N\fP" 5
To be documented\&.
.IP "\fB-P\fP" 5
This option causes \fBtrans386\fP to output
profiling information suitable for use with \fBprof\fP\fB(1)\fP or a
similar tool (see individual manual pages for details)\&. This option is
currently not supported on the Solaris platform\&.
.IP "\fB-Q\fP" 5
This option causes \fBtrans386\fP to quit before
processing its input files\&. This is particularly useful in conjunction
with \fB-V\fP\&.
.IP "\fB-R\fP\fIswitch\fP" 5
This option determines whether \fBtrans386\fP should
immediately round every floating point operation to its appropriate
range\&. This produces slower code, but is necessary for strict IEEE
conformance\&. The default is not to round after every operation\&.
.IP "\fB-U\fP\fIswitch\fP" 5
This option determines whether \fBtrans386\fP should
apply the "loop unrolling" optimisation\&. This optimisation is performed
by default\&.
.IP "\fB-V\fP" 5
This option causes \fBtrans386\fP to print its
version number and the version of the TDF specification it
supports\&.
.IP "\fB-W\fP\fIswitch\fP" 5
This option determines whether \fBtrans386\fP should
make string literals writable\&. At present the C producer does not make
use of this facility, so strings are writable\&.
.IP "\fB-X\fP" 5
This option disables all optimisations\&. All
\fBtrans386\fP&39;s optimisations are believed to be valid,
so that any error in optimisation is a genuine bug\&.
.IP "\fB-Z\fP" 5
This option causes \fBtrans386\fP to print the
version number of all the TDF capsules it decodes\&.
.IP "\fB-a\fP" 5
Always use a frame pointer\&. The default is to avoid using a frame
pointer whenever possible\&. The default results in better performance,
but in special cases where the stack is to be processed it may be
necessary to enforce the use of a frame pointer\&.
.IP "\fB-b\fP" 5
To be documented\&.
.IP "\fB-c\fP" 5
To be documented\&.
.IP "\fB-d\fP" 5
To be documented\&.
.IP "\fB-e\fP" 5
To be documented\&.
.IP "\fB-f\fP" 5
To be documented\&.
.IP "\fB-g\fP" 5
To be documented\&.
.IP "\fB-i\fP" 5
To be documented\&.
.IP "\fB-j\fP" 5
Do not use the \&.bss segment, always put data into the \&.data
segment even if it is zero\&. This should very rarely be needed\&. The
default is to use the \&.bss segment\&.
.IP "\fB-s\fP" 5
To be documented\&.
.SH "SEE ALSO"
.PP
\fBas\fP\fB(1)\fP,\fBprof\fP\fB(1)\fP, \fBtcc\fP\fB(1)\fP\&.
...\" created by instant / docbook-to-man, Sat 07 Aug 2004, 18:35
