# $TenDRA$



# Section 1 manpages
MAN=	680x0.sunos.trans.1 \
	80x86.cygwin32.trans.1 \
	80x86.freebsd.trans.1 \
	80x86.linux.trans.1 \
	80x86.netbsd.trans.1 \
	80x86.openbsd.trans.1 \
	80x86.sco.trans.1 \
	80x86.solaris.trans.1 \
	80x86.svr4.2.trans.1 \
	alpha.freebsd.trans.1 \
	alpha.osf1.trans.1 \
	hppa.hpux.trans.1 \
	mips.irix.trans.1 \
	mips.ultrix.trans.1 \
	power.aix.trans.1 \
	ppc601.aix.trans.1 \
	sparc.solaris.trans.1 \
	sparc.sunos.trans.1

.include "${.CURDIR}/../Makefile.inc"

.include "${.CURDIR}/../../../mk/base/tendra.prog.mk"

