# $TenDRA$


# We gotta include this first so our variables fill in for MAN1 below.

.include "${.CURDIR}/../../../mk/base/tendra.prog.mk"

# Section 1 manpages
MAN1=	${MACH_CPU}.${BUILD_OS}.trans.1

.include "${.CURDIR}/../Makefile.inc"
