# $Id$

NAME = tcpplus
SECTION = user/guides
THEMEFILENAME = website
DOCTOOLS_BASE = ../../../build

DIA = dia

XHTMLIMAGES = images/compile.png

include $(DOCTOOLS_BASE)/docs.mk

images/compile.png: images/compile.dia
	${DIA} -t png images/compile.dia

