# $TenDRA$

SRCDIRS+=	hppa/common

# installers/hppa/common
SRCS+=	c_arith_type.c codehere.c comment.c eval.c frames.c getregs.c glopt.c \
	guard.c hppadiags.c hppains.c inlinechoice.c inst_fmt.c is_worth.c \
	labels.c locate.c machine.c machine_toks.c makecode.c move.c muldvrem.c \
	needscan.c oprators.c proc.c regable.c regalloc.c regexps.c spec_tok.c \
	special.c tempdecs.c translat.c weights.c
