# $TenDRA$

.PATH : ${.CURDIR} ${.CURDIR}/../../../common

DATA=	K-PIC tcc_diag tcc_prof tdf_ext

INSTALL_ENV=	yes

# This lives in env/, and sucks in the env/common files.
.include "../../../Makefile.inc"

.include "../../../../../../mk/base/tendra.prog.mk"
