# $Id$

.include "Makefile.inc"


ENVFILE+=	default

ENVFILE+=	tcc_diag

ENVCOMMON+=	machines/common/env
ENVCOMMON+=	machines/${OSFAM}/common/env
ENVCOMMON+=	machines/${OSFAM}/mips/env/common

.include <tendra.env.mk>

