# $Id$

.include "Makefile.inc"


SUBDIR+=	trans-all.1
SUBDIR+=	trans386.1
SUBDIR+=	alphatrans.1
SUBDIR+=	hppatrans.1
SUBDIR+=	mipstrans.1
SUBDIR+=	powertrans.1
SUBDIR+=	sparctrans.1

.include <tendra.subdir.mk>

