# $Id$

.include "Makefile.inc"


SRCS+=	rule-check.c
SRCS+=	rule-firsts.c
SRCS+=	rule-mutate.c
SRCS+=	rule-simp.c
SRCS+=	rule-factor.c
SRCS+=	rule-lre.c
SRCS+=	rule-names.c
SRCS+=	rule-tail.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

