# $TenDRA$

.PATH :	${.CURDIR}/images

PDF_TITLE=	TDF Guide
PDF_SUBJECT=	TDF Guide

IMAGES_OBJ?=	guide1.obj guide2.obj guide3.obj

DOC?= book

SRCS=   book.xml

.include "../Makefile.inc"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
