# $Id$

# Copyright 2002-2011, The TenDRA Project.
# Copyright 1997, United Kingdom Secretary of State for Defence.
#
# See doc/copyright/ for the full copyright terms.


+IMPLEMENT "cae/xpg4", "errno.h.ts" ;

+CONST int EADDRINUSE, EADDRNOTAVAIL, EAFNOSUPPORT, EALREADY, EBADMSG ;
+CONST int ECONNABORTED, ECONNREFUSED, ECONNRESET, EDESTADDRREQ, EDQUOT ;
+CONST int EHOSTUNREACH, EINPROGRESS, EISCONN, ELOOP, EMSGSIZE, EMULTIHOP ;
+CONST int ENETDOWN, ENETUNREACH, ENOBUFS, ENODATA, ENOLINK, ENOPROTOOPT ;
+CONST int ENOSR, ENOSTR, ENOTCONN ;
+CONST int ENOTSOCK, EOPNOTSUPP, EOVERFLOW, EPROTO, EPROTONOSUPPORT ;
+CONST int EPROTOTYPE, ESTALE, ETIME, ETIMEDOUT, EWOULDBLOCK ;
