# $Id$

.include "Makefile.inc"

.include <tendra.base.mk>
.include <tendra.makedefs.mk>


MACHTOK_MAP   	= map_toks.tpl
MACHTOK_EXCEPT	= ${BLDARCH}-32fpr.tpl
MACHTOK_MODEL 	= ilp32.tpl
MACHTOK_FLOAT 	= ieee754-double.tpl
MACHTOK_INT   	= ${BLDARCH}-le.tpl
MACHTOK_CHAR   	= signed.tpl
MACHTOK_BITF  	= signed.tpl

.include <tendra.machtok.mk>

