/*
 *  AUTOMATICALLY GENERATED BY lexi VERSION 2.0
 */

#ifndef LEXI_GENERATED_HEADER_lexi__INCLUDED
#define LEXI_GENERATED_HEADER_lexi__INCLUDED

#ifndef LEX_EOF
#define LEX_EOF		256
#endif

extern void lexi_push(const int c);
extern int lexi_pop(void);
extern void lexi_flush(void);
extern int lexi_readchar(void);
enum lexi_groups {
	lexi_group_white = 0x01
};

/* true if the given character is present in the given group */
extern int lexi_group(enum lexi_groups group, int c);
extern int lexi_keyword(const char *identifier, int notfound);
/* lexer_state_definition */

typedef struct lexi_lexer_state_tag lexi_lexer_state;
extern lexi_lexer_state* lexi_current_lexer_state;
extern int lexi_read_token(lexi_lexer_state *state);
#endif
