# $Id$

.include "Makefile.inc"


CCOPTS+=	-I ../../common/reader
CCOPTS+=	-I ../../common/refactor

SRCS+=	bstack.c
SRCS+=	code_here.c
SRCS+=	comp_eq_exp.c
SRCS+=	dump_distr.c
SRCS+=	eval.c
SRCS+=	extern_adds.c
SRCS+=	frames.c
SRCS+=	getregs.c
SRCS+=	glopt.c
SRCS+=	guard.c
SRCS+=	handle_sregs.c
SRCS+=	inlinechoice.c
SRCS+=	inst_fmt.c
SRCS+=	is_worth.c
SRCS+=	labels.c
SRCS+=	locate.c
SRCS+=	machine.c
SRCS+=	machine_toks.c
SRCS+=	main.c
SRCS+=	makesymtab.c
SRCS+=	mips_ins.c
SRCS+=	mipsdiags.c
SRCS+=	move.c
SRCS+=	needs_scan.c
SRCS+=	new_code.c
SRCS+=	new_symbol.c
SRCS+=	oddtest.c
SRCS+=	operators.c
SRCS+=	psu_ops.c
SRCS+=	regable.c
SRCS+=	regalloc.c
SRCS+=	regexps.c
SRCS+=	spec.c
SRCS+=	spec_tok.c
SRCS+=	special.c
SRCS+=	syms.c
SRCS+=	tempdecs.c
SRCS+=	translate.c
SRCS+=	type_to_aux.c
SRCS+=	weights.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

