# $Id$

.include "Makefile.inc"

.include <tendra.base.mk>


ENVFILE+=	default

ENVCOMMON+=	machines/common/env
ENVCOMMON+=	machines/${OSFAM}/common/env
ENVCOMMON+=	toolchain/sun/common
ENVCOMMON+=	toolchain/sun/${BLDARCH}

.include <tendra.env.mk>

