# $Id$

.include "Makefile.inc"


ENVFILE+=	default

ENVFILE+=	tcc_prof

ENVCOMMON+=	machines/common/env
#ENVCOMMON+=	machines/${OSFAM}/common/env
ENVCOMMON+=	machines/${OSFAM}/${BLDARCH}/env/common

.include <tendra.env.mk>

