# $TenDRA$

PROG=	trans

# installers/hppa/hpux
SRCS=	hppatrans.c

# installers/hppa
.include "${.CURDIR}/../Makefile.inc"

# installers/
.include "${.CURDIR}/../../Makefile.inc"

.include "${.CURDIR}/../../../../mk/base/tendra.prog.mk"
