# $Id$

.include "Makefile.inc"


CCOPTS+=	-I ..
CCOPTS+=	-I .

SRCS+=	dg_aux.c
SRCS+=	dg_fns.c
SRCS+=	diag_fns.c
SRCS+=	mark_scope.c
SRCS+=	special_tok.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

