# $TenDRA$

.PATH : ${.OBJDIR}/../../../svid3.api

TCCFLAGS+=	-g

# Set TL_DIAG so we know that we're in the diag directory.
TL_DIAG=	yes

# Source defines for the api itself
.include "${.CURDIR}/../Makefile.inc"
