# $Id$

NAME=tpl
SOURCE=tpl.xml
PROJECT_NAME=tpl
PROJECT_URL=http://docs.tendra.org/
RESOURCES=../../style/docbook.css ../../style/common.css
CSSFILE=docbook.css
XHTMLSTYLE=../../xsl/tendra-docbook-chunked.xsl
XHTMLSTYLE_SINGLE=../../xsl/tendra-docbook-single.xsl

include ../../doctools/Mk/docbook.mk

