# $Id$

.include "Makefile.inc"


CCOPTS+=	-I ..
CCOPTS+=	-I .

SRCS+=	special.c
SRCS+=	special_arith.c
SRCS+=	special_call.c
SRCS+=	special_diag.c
SRCS+=	special_alloc.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

