# $Id$

NAME=guide
SOURCE=guide.xml
PROJECT_NAME=calculus
PROJECT_URL=http://docs.tendra.org/
RESOURCES=../style/docbook.css ../style/common.css images/calculus.png
CSSFILE=docbook.css
XHTMLSTYLE=../xsl/tendra-docbook-chunked.xsl
XHTMLSTYLE_SINGLE=../xsl/tendra-docbook-single.xsl

include ../doctools/Mk/docbook.mk

