# $TenDRA$

PROG=	trans

# installers/power/aix
SRCS=	powertrans.c

# installers/power
.include "${.CURDIR}/../Makefile.inc"

# installers/
.include "${.CURDIR}/../../Makefile.inc"

.include "${.CURDIR}/../../../../mk/base/tendra.prog.mk"
