# $TenDRA$

.include "../Makefile.inc"

.PATH :	${.CURDIR}/images

IMAGES_OBJ?=	capsule1.obj capsule2.obj capsule3.obj capsule4.obj

DOC?= book

SRCS=   book.sgml

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
