# $TenDRA$

.PATH :	${.CURDIR}/images

PDF_TITLE=	TDF Specification
PDF_SUBJECT=	TDF Specification

IMAGES_OBJ?=	capsule1.obj capsule2.obj capsule3.obj capsule4.obj

DOC?= book

SRCS=   book.xml

.include "../Makefile.inc"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
