# $Id$

# This is a placeholder for tendra-doc to override.
DOCTOOLS_BASE ?= ../../build

all:
	cd man && $(MAKE) all DOCTOOLS_BASE=../$(DOCTOOLS_BASE)

clean:
	cd man && $(MAKE) clean DOCTOOLS_BASE=../$(DOCTOOLS_BASE)

