# $TenDRA$

PDF_TITLE=	TDF Diagnostic Specification
PDF_SUBJECT=	TDF Diagnostic Specification

DOC?= book

SRCS=   book.sgml


.include "../Makefile.inc"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
