/* $Id$ */

/*
 * Copyright 2002-2011, The TenDRA Project.
 * Copyright 1997, United Kingdom Secretary of State for Defence.
 *
 * See doc/copyright/ for the full copyright terms.
 */

#ifndef OUTPUT_H
#define OUTPUT_H

#include <stdio.h>

/*
 * Common output routines shared between multiple languages.
 * These are used by the output-* code generation backends.
 */


enum output_comment {
	OUTPUT_COMMENT_C90,	/* block style C comments */
	OUTPUT_COMMENT_C99	/* single-line C comments */
};


/*
 * OUTPUT INDENTATION
 *
 * This routine outputs an indentation of d.
 */
void
output_indent(FILE *, unsigned int depth);


/*
 * COMMENT FILE
 *
 * cat input into output, commenting as appropiate.
 * Returns false if the input file was found to have
 * contained an illegal comment.
 */
int
output_comment_file(enum output_comment, FILE *output, FILE *input);

/*
 * OUTPUT GENERATED BY LEXI Version
 *
 * This routine outputs a statement stating that the file is automatically
 * generated.
 */
void
output_generated_by_lexi(enum output_comment, FILE *out);

#endif

