/*
 * Copyright 2002-2011, The TenDRA Project.
 * Copyright 1997, United Kingdom Secretary of State for Defence.
 *
 * See doc/copyright/ for the full copyright terms.
 */

/* AUTOMATICALLY GENERATED BY %ZX VERSION %ZV FROM TDF %VA.%VB */

#include <stdio.h>

#include "consfile.h"
#include "defs.h"
#include "syntax.h"

/*
 * The table is sorted by piping it through consfile.awk:
 *
 * $ make_tdf=$TENDRA/make_tdf/obj/src/make_tdf
 * $ db=$TENDRA/tdf/db/def_4_0.db
 * $ cd $TENDRA/tpl/src
 * $ $make_tdf $db templ/consfile.c - | awk -f templ/consfile.awk > consfile.c
 *
 */

Constructs constructs [] = {
/* lines below | LC_ALL=C sort */
@use exp
@special callees
@special procprops
@special string
@special exp apply_general_proc
@special exp apply_proc
@special exp case
@special exp identify
@special exp labelled
@special exp make_floating
@special exp make_general_proc
@special exp make_int
@special exp make_proc
@special exp obtain_tag
@special exp sequence
@special exp tail_call
@special exp variable
@special alignment obtain_al_tag
@special error_treatment error_jump
@special nat make_nat
@special token use_tokdef
@loop sort
@if sort.basic
@if !sort.special
@loop sort.cons
@if cons.simple
{ "%CN", %SN_t, c_%CN },
@endif
@end
@endif
@endif
@end
/* lines above | LC_ALL=C sort */
} ;
