# $TenDRA$

SRCDIRS=	c/syntax common common/construct common/obj_templ \
		common/output common/parse common/utility 

PROG = tdfc2

# c/syntax
SRCS=	syntax1.c syntax2.c syntax3.c

.include "${.CURDIR}/../Makefile.inc"

.include "${.CURDIR}/../../../mk/base/tendra.prog.mk"
