# $Id$

.include "Makefile.inc"


CCOPTS+=	-I ../construct
CCOPTS+=	-I ../diag
CCOPTS+=	-I ../linkinfo
CCOPTS+=	-I ../reader
CCOPTS+=	-I .

SRCS+=	refactor.c
SRCS+=	refactor_id.c
SRCS+=	refactor_ext.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

