# $Id$

.include "Makefile.inc"

CCOPTS+=	-I${.CURDIR}/../../shared
CCOPTS+=	-I${.CURDIR}/..

SRCS+=	arg-data.c
SRCS+=	map-entry.c
SRCS+=	name-entry.c
SRCS+=	name-table.c
SRCS+=	shape-table.c
SRCS+=	tdf-write.c
SRCS+=	unit-table.c
SRCS+=	capsule.c
SRCS+=	map-table.c
SRCS+=	name-key.c
SRCS+=	shape-entry.c
SRCS+=	tdf-read.c
SRCS+=	unit-entry.c
SRCS+=	library.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

