# $Id$

.include "Makefile.inc"


#CCOPTS+=	-I ../../common

SRCS+=	alpha_ins.c
SRCS+=	bstack.c
SRCS+=	code_here.c
SRCS+=	coder.c
SRCS+=	comp_eq_exp.c
SRCS+=	cross.c
SRCS+=	diag_out.c
SRCS+=	symdiag_out.c
SRCS+=	dump_distr.c
SRCS+=	eval.c
SRCS+=	extern_adds.c
SRCS+=	fail.c
SRCS+=	file.c
SRCS+=	float.c
SRCS+=	frames.c
SRCS+=	getregs.c
SRCS+=	glopt.c
SRCS+=	guard.c
SRCS+=	handle_sregs.c
SRCS+=	inlinechoice.c
SRCS+=	inst_fmt.c
SRCS+=	is_worth.c
SRCS+=	labels.c
SRCS+=	locate.c
SRCS+=	machine.c
SRCS+=	machine_toks.c
SRCS+=	main.c
SRCS+=	makesymtab.c
SRCS+=	move.c
SRCS+=	oddtest.c
SRCS+=	operators.c
SRCS+=	out_ba.c
SRCS+=	pseudo.c
SRCS+=	regable.c
SRCS+=	regalloc.c
SRCS+=	regexps.c
SRCS+=	scan.c
SRCS+=	spec.c
SRCS+=	spec_tok.c
SRCS+=	special.c
SRCS+=	symbol.c
SRCS+=	syms.c
SRCS+=	tempdecs.c
SRCS+=	translate.c
SRCS+=	type_to_aux.c
SRCS+=	weights.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

