# $Id$

.include "Makefile.inc"

.include <tendra.base.mk>
.include <tendra.makedefs.mk>


ABI_EXCEPT   = ${BLDARCH}.tpl
ABI_MODEL    = ilp32.tpl
ABI_FLOAT    = ieee754-quad.tpl
ABI_INT      = ${BLDARCH}.tpl
ABI_CHAR     = signed.tpl
ABI_BITFIELD = signed.tpl
ABI_ALIGN    = char.tpl
ABI_STRUCT   = min8.tpl
ABI_PUN      = generic.tpl
ABI_STACK    = builtin.tpl
ABI_VA       = c89.tpl

.include <tendra.abi.mk>

