# $Id$

.include "Makefile.inc"


CCOPTS+=	-I ../construct
CCOPTS+=	-I ../linkinfo
CCOPTS+=	-I ../reader
CCOPTS+=	-I .

SRCS+=	dg_aux.c
SRCS+=	dg_fns.c
SRCS+=	diag_fns.c
SRCS+=	diag_info.c
SRCS+=	mark_scope.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

