/*
 * Copyright 2002-2011, The TenDRA Project.
 * Copyright 1997, United Kingdom Secretary of State for Defence.
 *
 * See doc/copyright/ for the full copyright terms.
 */

    
    
    
    
    

#ifndef BITS_INCLUDED
#define BITS_INCLUDED


/*
    BIT VALUES

    These macros give the number of bits needed to encode the various
    enumeration and union types.  This file is automatically generated
    from algebra c_class (version 1.1) by calculus (version 1.3).
*/

#define BITS_cv			5
#define BITS_ntype		5
#define BITS_btype		23
#define BITS_cinfo		32
#define BITS_cusage		4
#define BITS_dspec		32
#define BITS_qual		3
#define BITS_ntest		4
#define BITS_rmode		3

#define BITS_itype		3
#define BITS_ftype		3
#define BITS_ctype		1
#define BITS_graph		1
#define BITS_virt		3
#define BITS_etype		1
#define BITS_type		5
#define BITS_hashid		3
#define BITS_id			5
#define BITS_member		2
#define BITS_nspace		4
#define BITS_nat		3
#define BITS_flt		1
#define BITS_str		1
#define BITS_exp		7
#define BITS_off		4
#define BITS_tok		4
#define BITS_inst		2
#define BITS_err		2

#define BITS_cv_qual		3
#define BITS_ellipsis		4
#define BITS_lex		9


#endif
