/* $Id$ */

/*
 * Copyright 2002-2011, The TenDRA Project.
 * Copyright 1997, United Kingdom Secretary of State for Defence.
 *
 * See doc/copyright/ for the full copyright terms.
 */

    
    
    
    
    

#ifndef ERR_EXT_INCLUDED
#define ERR_EXT_INCLUDED


/*
    ERROR OPERATIONS

    This file describes the operations on errors.  It includes the simple
    operations generated by the calculus tool and extends them by a number
    of hand crafted operations.  This file is automatically generated from
    algebra c_class (version 1.1) by calculus (version 1.3).
*/

#include "err_ops.h"

#define SIZE_err_simple		4

#define MAKE_err_simple_args(A, B, C, E)\
    {\
	unsigned sz_ = (C);\
	c_class *err_ = GEN_c_class(SIZE_err_simple + sz_, TYPEID_err);\
	err_->ag_tag = err_simple_tag ;\
	COPY_int(err_severity(err_), (A));\
	COPY_int(err_simple_number(err_), (B));\
	COPY_unsigned(err_simple_size(err_), sz_);\
	(E) = err_ ;\
    }

#define DESTROY_err_simple_args(E)\
    {\
	ERROR err_ = (E);\
	unsigned sz_ = DEREF_unsigned(err_simple_size(err_));\
	destroy_c_class(err_, SIZE_err_simple + sz_);\
    }

#define err_arg(E, A, T)	((E) + (SIZE_err_simple + (A)))


#endif
