# $Id$

.include "Makefile.inc"


CCOPTS+=	-I ../../common

SRCS+=	assembler.c
SRCS+=	c_arith_type.c
SRCS+=	codec.c
SRCS+=	coder.c
SRCS+=	cproc.c
SRCS+=	dw2_extra.c
SRCS+=	evaluate.c
SRCS+=	glopt.c
SRCS+=	inlinechoice.c
SRCS+=	instr.c
SRCS+=	instr386.c
SRCS+=	is_worth.c
SRCS+=	localflags.c
SRCS+=	machine_toks.c
SRCS+=	main.c
SRCS+=	operand.c
SRCS+=	out.c
SRCS+=	overlap.c
SRCS+=	reg_record.c
SRCS+=	scan2.c
SRCS+=	spec.c
SRCS+=	spec_tok.c
SRCS+=	translate.c
SRCS+=	tv_callees.c
SRCS+=	weights.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

