# $Id$

.include "Makefile.inc"


SRCS+=	baseinfo.cc
SRCS+=	cmath.cc
SRCS+=	cstring.cc
SRCS+=	cwchar.cc
SRCS+=	exception.cc
SRCS+=	new.cc
SRCS+=	new1.cc
SRCS+=	new2.cc
SRCS+=	new3.cc
SRCS+=	new4.cc
SRCS+=	new5.cc
SRCS+=	new6.cc
SRCS+=	new7.cc
SRCS+=	new8.cc
SRCS+=	pure.cc
SRCS+=	term.cc
SRCS+=	typeinfo.cc
SRCS+=	what.cc

.include <tendra.obj.mk>


LIB=	cpp

.include <tendra.lib.mk>

