# $Id$

.include "Makefile.inc"

.include <tendra.base.mk>
.include <tendra.makedefs.mk>


MACHTOK_DEP   	= dep_toks.tpl
MACHTOK_MAP   	= map_toks.tpl
MACHTOK_EXCEPT	= ${BLDARCH}.tpl
MACHTOK_MODEL 	= ilp32.tpl
MACHTOK_FREP  	= ieee754-quad.tpl

.include <tendra.machtok.mk>

