# $Id$

NAME=unix-validation
SOURCE=unix-validation.xml
PROJECT_NAME=unix-validation
PROJECT_URL=http://docs.tendra.org/
RESOURCES=../../style/docbook.css ../../style/common.css
CSSFILE=docbook.css
XHTMLSTYLE=../../xsl/tendra-docbook-chunked.xsl
XHTMLSTYLE_SINGLE=../../xsl/tendra-docbook-single.xsl

include ../../doctools/Mk/docbook.mk

