# $Id$

.include "Makefile.inc"


ENVFILE=	default

ENVFILE+=	Goption
ENVFILE+=	K-PIC

ENVFILE+=	Xa
ENVFILE+=	Xc
ENVFILE+=	Xp
ENVFILE+=	Xs
ENVFILE+=	Xt
ENVFILE+=	Xw

ENVFILE+=	tcc_diag
ENVFILE+=	tcc_prof

ENVCOMMON+=	machines/common/env
ENVCOMMON+=	machines/common/arch/${BLDARCH}/env
ENVCOMMON+=	machines/${OSFAM}/common/env

.include <tendra.env.mk>

