# $Id$

.include "Makefile.inc"


ENVFILE=	default

ENVFILE+=	Goption
ENVFILE+=	K-PIC

ENVCOMMON+=	machines/common/env
ENVCOMMON+=	machines/common/arch/${BLDARCH}/env
ENVCOMMON+=	machines/${OSFAM}/common/env

.include <tendra.env.mk>

