# $Id$

.include "Makefile.inc"


ENVFILE+=	default

ENVFILE+=	K-P5
ENVFILE+=	K-PIC
ENVFILE+=	K-frame
ENVFILE+=	K-i386
ENVFILE+=	K-i486
ENVFILE+=	K-noframe

ENVFILE+=	Z-p
ENVFILE+=	Z-p1
ENVFILE+=	Z-p2
ENVFILE+=	Z-p4

ENVFILE+=	tcc_diag
ENVFILE+=	tcc_prof

ENVCOMMON+=	machines/common/env
ENVCOMMON+=	machines/${OSFAM}/common/env
#ENVCOMMON+=	machines/${OSFAM}/${BLDARCH}/env/common

.include <tendra.env.mk>

