# $TenDRA$

PROG=	trans

# installers/680x0/sunos
SRCS=	main.c

# installers/680x0
.include "${.CURDIR}/../Makefile.inc"

# installers/
.include "${.CURDIR}/../../Makefile.inc"

.include "${.CURDIR}/../../../../mk/base/tendra.prog.mk"
