# Copyright 2002-2011, The TenDRA Project.
# Copyright 1997, United Kingdom Secretary of State for Defence.
#
# See doc/copyright/ for the full copyright terms.


# Properties and atoms (4.3)

+USE "x5/lib", "X11/X.h.ts" ;

+CONST Atom XA_PRIMARY, XA_SECONDARY ;

+CONST Atom XA_CUT_BUFFER0, XA_CUT_BUFFER1, XA_CUT_BUFFER2, XA_CUT_BUFFER3 ;
+CONST Atom XA_CUT_BUFFER4, XA_CUT_BUFFER5, XA_CUT_BUFFER6, XA_CUT_BUFFER7 ;
+CONST Atom XA_RGB_BEST_MAP, XA_RGB_BLUE_MAP, XA_RGB_DEFAULT_MAP ;
+CONST Atom XA_RGB_GRAY_MAP, XA_RGB_GREEN_MAP, XA_RGB_RED_MAP ;
+CONST Atom XA_RESOURCE_MANAGER, XA_WM_CLASS, XA_WM_CLIENT_MACHINE ;
+CONST Atom XA_WM_COLORMAP_WINDOWS, XA_WM_COMMAND, XA_WM_HINTS ;
+CONST Atom XA_WM_ICON_NAME, XA_WM_ICON_SIZE, XA_WM_NAME ;
+CONST Atom XA_WM_NORMAL_HINTS, XA_WM_PROTOCOLS, XA_WM_STATE ;
+CONST Atom XA_WM_TRANSIENT_FOR ;

+CONST Atom XA_ARC, XA_ATOM, XA_BITMAP, XA_CARDINAL, XA_COLORMAP ;
+CONST Atom XA_CURSOR, XA_DRAWABLE, XA_FONT, XA_INTEGER, XA_PIXMAP ;
+CONST Atom XA_POINT, XA_RGB_COLOR_MAP, XA_RECTANGLE, XA_STRING ;
+CONST Atom XA_VISUALID, XA_WINDOW, XA_WM_SIZE_HINTS ;

+CONST Atom XA_MIN_SPACE, XA_NORM_SPACE, XA_MAX_SPACE, XA_END_SPACE ;
+CONST Atom XA_SUPERSCRIPT_X, XA_SUPERSCRIPT_Y, XA_SUBSCRIPT_X ;
+CONST Atom XA_SUBSCRIPT_Y, XA_UNDERLINE_POSITION, XA_UNDERLINE_THICKNESS ;
+CONST Atom XA_FONT_NAME, XA_FULL_NAME, XA_STRIKEOUT_DESCENT ;
+CONST Atom XA_STRIKEOUT_ASCENT, XA_ITALIC_ANGLE, XA_X_HEIGHT ;
+CONST Atom XA_QUAD_WIDTH, XA_WEIGHT, XA_POINT_SIZE, XA_RESOLUTION ;
+CONST Atom XA_COPYRIGHT, XA_NOTICE, XA_FAMILY_NAME, XA_CAP_HEIGHT ;
