# $Id$

.include "Makefile.inc"


SUBDIR+=	env
SUBDIR+=	tokens

.include <tendra.subdir.mk>


APIS+=  ansi
#APIS+=	iso
#APIS+=	cpp
#APIS+=	system

#APIS+=	posix
#APIS+=	posix1
#APIS+=	posix2
#APIS+=	xpg3
#APIS+=	xpg4
#APIS+=	unix95
#APIS+=	svid3

#APIS+=	gcc
#APIS+=	bsd_extn

.include <tendra.api.mk>

