# $Id$

.include "Makefile.inc"


ENVFILE+=	Z-p
ENVFILE+=	Z-p1
ENVFILE+=	Z-p2
ENVFILE+=	Z-p4

ENVFILE+=	K-i386
ENVFILE+=	K-i486
ENVFILE+=	K-P5

ENVFILE+=	K-frame
ENVFILE+=	K-noframe

ENVFILE+=	K-PIC

ENVFILE+=	tcc_prof

.include <tendra.env.mk>

