# $Id$

.include "Makefile.inc"


STARTUPSUBDIR+=	bounds
STARTUPSUBDIR+=	literal
STARTUPSUBDIR+=	modes
STARTUPSUBDIR+=	promotion
STARTUPSUBDIR+=	charmap
STARTUPSUBDIR+=	lang

.include <tendra.startup.mk>

