# $Id$

.include "Makefile.inc"


STARTUPSUBDIR+=	bounds
STARTUPSUBDIR+=	literal
STARTUPSUBDIR+=	modes
STARTUPSUBDIR+=	modes.cpp
STARTUPSUBDIR+=	promotion
STARTUPSUBDIR+=	charmap

.include <tendra.startup.mk>

