# $Id$

.include "Makefile.inc"


STARTUPSUBDIR+=	Bounds.32
STARTUPSUBDIR+=	Bounds.ansi
STARTUPSUBDIR+=	Literal
STARTUPSUBDIR+=	Modes
STARTUPSUBDIR+=	Modes.cpp
STARTUPSUBDIR+=	Promotion
STARTUPSUBDIR+=	charmap

.include <tendra.startup.mk>

