# $Id$

.include "Makefile.inc"


MACHTOK_DEP   	= dep_toks.tpl
MACHTOK_MAP   	= map_toks.tpl
MACHTOK_VAR   	= var_toks.tpl  # Note hpux/hppa has its own var_toks.tpl
MACHTOK_EXCEPT	= except_toks.tpl
MACHTOK_MODEL 	= ilp32.tpl

.include <tendra.machtok.mk>

