# $TenDRA$

.PATH : ${.OBJDIR}/../../svid3.api

# Defs for lib/apis/diag
.include "${.CURDIR}/../Makefile.inc"

# Defs for lib/apis
.include "${.CURDIR}/../../Makefile.inc"

# Source for the api itself
.include "${.CURDIR}/../../svid3/Makefile.inc"

.include "${.CURDIR}/../../../../../mk/base/tendra.prog.mk"
