# $Id$

.include "Makefile.inc"


ENVFILE+=	default

ENVFILE+=	K-PIC

ENVFILE+=	tcc_diag
ENVFILE+=	tcc_prof
ENVFILE+=	tdf_ext

ENVCOMMON+=	machines/common/env
#ENVCOMMON+=	machines/${OSFAM}/common/env

.include <tendra.env.mk>

