# $TenDRA$

.PATH : ${.OBJDIR}/../../../unix95.api

TCCFLAGS+=	-g

# Source defines for the api itself
.include "${.CURDIR}/../Makefile.inc"

# Flags for tspec
.include "${.CURDIR}/../../Makefile.inc"
