# $Id$

.include "Makefile.inc"


CCOPTS+=	-I ..
CCOPTS+=	-I .

SRCS+=	new_symbol.c
SRCS+=	makesymtab.c
SRCS+=	bstack.c
SRCS+=	syms.c
SRCS+=	type_to_aux.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

