# $Id$

all:
	cd doc && ${MAKE} all
	cd src && ${MAKE} all

test:
	cd tests && ${MAKE} test

clean:
	cd src && ${MAKE} clean
	cd doc && ${MAKE} clean

install:
	cd src && ${MAKE} install
	cd doc && ${MAKE} install
	cd examples && ${MAKE} install

