# $Id$

.include "Makefile.inc"


SRCS+=	action.c
SRCS+=	arg.c
SRCS+=	cmd.c
SRCS+=	entry.c
SRCS+=	group.c
SRCS+=	keyword.c
SRCS+=	param.c
SRCS+=	trie.c
SRCS+=	localnames.c
SRCS+=	trans.c
SRCS+=	zone.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

