# $Id$

.include "Makefile.inc"


SRCS+=	action.c
SRCS+=	arg.c
SRCS+=	cmd.c
SRCS+=	entry.c
SRCS+=	group.c
SRCS+=	keyword.c
SRCS+=	zone.c
SRCS+=	trie.c
SRCS+=	type.c
SRCS+=	typetuple.c
SRCS+=	localnames.c
SRCS+=	trans.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

