# $Id$

.include "Makefile.inc"


CCOPTS+=	-I${.CURDIR}/../shared

SRCS+=	char.c
SRCS+=	group.c
SRCS+=	instruction.c
SRCS+=	keyword.c
SRCS+=	tree.c
SRCS+=	zone.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

