/*
    		 Crown Copyright (c) 1997
    
    This TenDRA(r) Computer Program is subject to Copyright
    owned by the United Kingdom Secretary of State for Defence
    acting through the Defence Evaluation and Research Agency
    (DERA).  It is made available to Recipients with a
    royalty-free licence for its use, reproduction, transfer
    to other parties and amendment for any purpose not excluding
    product development provided that any such use et cetera
    shall be deemed to be acceptance of the following conditions:-
    
        (1) Its Recipients shall ensure that this Notice is
        reproduced upon any copies or amended versions of it;
    
        (2) Any amended version of it shall be clearly marked to
        show both the nature of and the organisation responsible
        for the relevant amendment or amendments;
    
        (3) Its onward transfer from a recipient to another
        party shall be deemed to be that party's acceptance of
        these conditions;
    
        (4) DERA gives no warranty or assurance as to its
        quality or suitability for any purpose and DERA accepts
        no liability whatsoever in relation to any use to which
        it may be put.
*/


#ifndef BITS_INCLUDED
#define BITS_INCLUDED


/*
    BIT VALUES

    These macros give the number of bits needed to encode the various
    enumeration and union types.  This file is automatically generated
    from algebra c_class (version 1.1) by calculus (version 1.2).
*/

#define BITS_cv			5
#define BITS_ntype		5
#define BITS_btype		23
#define BITS_cinfo		32
#define BITS_cusage		4
#define BITS_dspec		32
#define BITS_qual		3
#define BITS_ntest		4
#define BITS_rmode		3

#define BITS_itype		3
#define BITS_ftype		3
#define BITS_ctype		1
#define BITS_graph		1
#define BITS_virt		3
#define BITS_etype		1
#define BITS_type		5
#define BITS_hashid		3
#define BITS_id			5
#define BITS_member		2
#define BITS_nspace		4
#define BITS_nat		3
#define BITS_flt		1
#define BITS_str		1
#define BITS_exp		7
#define BITS_off		4
#define BITS_tok		4
#define BITS_inst		2
#define BITS_err		2

#define BITS_cv_qual		3
#define BITS_ellipsis		4
#define BITS_lex		9


#endif
