# $Id$

.include "Makefile.inc"


ENVFILE+=	tcc_prof
ENVFILE+=	tcc_diag

ENVFILE+=	K-aout
ENVFILE+=	K-pic
ENVFILE+=	K-nopic
ENVFILE+=	K-ieee
ENVFILE+=	K-noieee
ENVFILE+=	K-prom

.include <tendra.env.mk>

