# $Id$

.include "Makefile.inc"


ENVFILE+=	default

ENVFILE+=	K-P5
ENVFILE+=	K-aout
ENVFILE+=	K-frame
ENVFILE+=	K-noframe

ENVFILE+=	Z-p
ENVFILE+=	Z-p1
ENVFILE+=	Z-p2
ENVFILE+=	Z-p4

ENVFILE+=	system
ENVFILE+=	system+
ENVFILE+=	tcc_prof
ENVFILE+=	tdf_ext

ENVCOMMON+=	machines/common/env
ENVCOMMON+=	machines/${OSFAM}/common/env
#ENVCOMMON+= machines/${OSFAM}/${BLDARCH}/env/common

.include <tendra.env.mk>

