# Use the FreeBSD DocBook makefiles for now, until I get the makefiles in
# place.
#
# $Id$

DOC?= FAQ
FORMATS?= html html-split pdf

SRCS=	FAQ.sgml

DOC_PREFIX?= ${.CURDIR}/..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
