# $Id$

.include "Makefile.inc"


DOC=       	${.CURDIR:T}
DOC_PREFIX=	${.CURDIR:H:T}
DOC_DPADD+= \
	bibliography.xml               \
	capsulesunits.xml              \
	conclusion.xml                 \
	constants.xml                  \
	controlflow.xml                \
	models.xml                     \
	offsetexpansion.xml            \
	operations.xml                 \
	portability.xml                \
	preface.xml                    \
	proceduresandlocals.xml        \
	shapesalignmentsoffsets.xml    \
	sortstokens.xml                \
	tdf.xml                        \
	tokensandapis.xml              \
	transformations.xml            \
	valuesvariablesassignments.xml

.include <tendra.doc.mk>
