# $Id$

.include "Makefile.inc"


ENVFILE+=	default

ENVFILE+=	Z-p
ENVFILE+=	Z-p1
ENVFILE+=	Z-p2
ENVFILE+=	Z-p4

ENVFILE+=	tcc_diag
ENVFILE+=	tcc_prof

ENVCOMMON+=	machines/common/env
ENVCOMMON+=	machines/common/arch/${BLDARCH}/env
#ENVCOMMON+=	machines/${OSFAM}/common/env

.include <tendra.env.mk>

