# $Id$

.include "Makefile.inc"

.include <tendra.base.mk>


ENVFILE+=	default

ENVFILE+=	tcc_prof

ENVCOMMON+=	machines/common/env
ENVCOMMON+=	machines/common/arch/${BLDARCH}/env
ENVCOMMON+=	machines/${OSFAM}/common/env

.include <tendra.env.mk>

