# $TenDRA$

SRCDIRS+=	sparc/common

# installers/sparc/common

SRCS+=	codehere.c comment.c dw2_extra.c eval.c getregs.c glopt.c guard.c \
	inlinechoice.c inst_fmt.c is_worth.c labels.c locate.c machine.c \
	machine_toks.c makecode.c move.c muldvrem.c needscan.c oprators.c \
	proc.c regable.c regalloc.c regexps.c sparcins.c sparctrans.c \
	spec_tok.c special.c tempdecs.c translat.c weights.c
