# $Id$

.include "Makefile.inc"

.include <tendra.base.mk>
.include <tendra.makedefs.mk>


MACHTOK_EXCEPT   = ${BLDARCH}-64fpr.tpl
MACHTOK_MODEL    = ilp32.tpl
MACHTOK_FLOAT    = ieee754-double.tpl
MACHTOK_INT      = ${BLDARCH}-le.tpl
MACHTOK_CHAR     = unsigned.tpl
MACHTOK_BITFIELD = signed.tpl
MACHTOK_ALIGN    = char.tpl
MACHTOK_STRUCT   = min8.tpl
MACHTOK_PUN      = generic.tpl
MACHTOK_STACK    = offset.tpl
MACHTOK_VA       = c89.tpl

.include <tendra.machtok.mk>

