# $Id$

# The order might seem weird, but it has all to do with dependencies on another
# API and minimizing the build costs.
SUBDIR=	ansi iso posix cpp gcc posix1 posix2 unix95 xpg3 xpg4 svid3 bsd_extn

.include "Makefile.inc"
