# $Id$

.include "Makefile.inc"


CCOPTS+=	-I construct
CCOPTS+=	-I utility
CCOPTS+=	-I parse
CCOPTS+=	-I obj_c
CCOPTS+=	-I output

SRCS+=	main.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

