# $Id$

.include "Makefile.inc"


CCOPTS+=	-I ../construct
CCOPTS+=	-I ../diag
CCOPTS+=	-I ../reader
CCOPTS+=	-I ../refactor
CCOPTS+=	-I .

SRCS+=	li_fns.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

