# $Id$

TARGETS = bistream.o bitvec.o bostream.o common.o cstring-list.o \
	cstring.o dalloc.o dstring.o error.o exception.o \
	istream.o nstring-list.o ostream.o

CFLAGS = -I ../../include

REMOVE = rm -f

test: $(TARGETS)

clean:
	${REMOVE} ${TARGETS}

