# $Id$

.include "Makefile.inc"

.include <tendra.base.mk>


ENVFILE+=	default

ENVFILE+=	tdf_ext

ENVCOMMON+=	machines/common/env
ENVCOMMON+=	machines/${OSFAM}/common/env
ENVCOMMON+=	toolchain/hp/common
#ENVCOMMON+=	toolchain/hp/${BLDARCH}

.include <tendra.env.mk>

