# $TenDRA$

# Nothing is actually built in here, so we don't need an object directory.
NO_OBJDIR=	yes

API=	xpg4

.include "../Makefile.inc"

.if exists (${OBJ_DIR}.api/Makefile)
.include "${OBJ_DIR}.api/Makefile"
.endif
