# $Id$

.include "Makefile.inc"


ENVFILE+=	default

ENVFILE+=	posix_lib
ENVFILE+=	static
ENVFILE+=	tcc_diag
ENVFILE+=	tcc_prof

ENVCOMMON+=	machines/common/env
#ENVCOMMON+=	machines/${OSFAM}/common/env

.include <tendra.env.mk>

