# $Id$

.include "Makefile.inc"

.include <tendra.base.mk>


ENVFILE+=	default

ENVFILE+=	posix_lib
ENVFILE+=	static

ENVCOMMON+=	machines/common/env
ENVCOMMON+=	machines/${OSFAM}/common/env

.include <tendra.env.mk>

