# $Id$

.include "Makefile.inc"

CCOPTS+=	-I${.CURDIR}/../shared
CCOPTS+=	-I${.CURDIR}/..

SRCS+=	builder.c
SRCS+=	contents.c
SRCS+=	extract.c
SRCS+=	linker.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

