# $TenDRA$

PDF_TITLE=	TenDRA calculus manpage
PDF_SUBJECT=	TenDRA calculus manpage

DOC?= refentry

SRCS=   refentry.sgml

.include "../Makefile.inc"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
