/* Automatically generated by 'BUILD_ERRORS' */

#include "os-interface.h"

/* Header from input file '/u/g/release/Source/src/tools/tld/errors/arg-data.e' */
#include "dstring.h"
#include "name-key.h"

/* Header from input file '/u/g/release/Source/src/tools/tld/errors/arg-parse.e' */
#include "arg-parse.h"

/* Header from input file '/u/g/release/Source/src/tools/tld/errors/builder.e' */

/* Header from input file '/u/g/release/Source/src/tools/tld/errors/capsule.e' */
#include "capsule.h"
#include "istream.h"
#include "name-key.h"

/* Header from input file '/u/g/release/Source/src/tools/tld/errors/contents.e' */

/* Header from input file '/u/g/release/Source/src/tools/tld/errors/error-file.e' */
#include "istream.h"

/* Header from input file '/u/g/release/Source/src/tools/tld/errors/extract.e' */

/* Header from input file '/u/g/release/Source/src/tools/tld/errors/for-osif.e' */
#include "exception.h"

/* Header from input file '/u/g/release/Source/src/tools/tld/errors/library.e' */
#include "library.h"

/* Header from input file '/u/g/release/Source/src/tools/tld/errors/linker.e' */
#include "dstring.h"
#include "name-key.h"

/* Header from input file '/u/g/release/Source/src/tools/tld/errors/main.e' */
#include "arg-parse.h"

/* Header from input file '/u/g/release/Source/src/tools/tld/errors/name-entry.e' */
#include "dstring.h"
#include "name-key.h"

/* Header from input file '/u/g/release/Source/src/tools/tld/errors/rename-file.e' */

/* Header from input file '/u/g/release/Source/src/tools/tld/errors/shape-entry.e' */

/* Header from input file '/u/g/release/Source/src/tools/tld/errors/tdf-read.e' */
#include "tdf-read.h"


/* Error function declarations */

extern void E_tld_multiple_debug_files
	PROTO_S ((void));
extern void E_tld_cannot_open_debug_file
	PROTO_S ((CStringP));
extern void E_tld_multiple_output_files
	PROTO_S ((void));
extern void E_tld_multiple_unit_files
	PROTO_S ((void));
extern void E_multiply_renamed_name
	PROTO_S ((NStringP, NameKeyP));
extern void E_arg_parse_unknown_option
	PROTO_S ((CStringP, ArgUsageP));
extern void E_arg_parse_unknown_short_opt
	PROTO_S ((CStringP, CStringP, ArgUsageP));
extern void E_arg_parse_ambiguous_option
	PROTO_S ((CStringP, ArgUsageP));
extern void E_arg_parse_missing_argument
	PROTO_S ((CStringP, ArgUsageP));
extern void E_arg_parse_missing_short_arg
	PROTO_S ((CStringP, CStringP, ArgUsageP));
extern void E_duplicate_capsule_name
	PROTO_S ((CStringP));
extern void E_cannot_open_unit_set_file
	PROTO_S ((CStringP));
extern void E_unit_set_expected_quote
	PROTO_S ((IStreamP));
extern void E_unit_set_illegal_escape
	PROTO_S ((IStreamP));
extern void E_unit_set_eof_in_name
	PROTO_S ((IStreamP));
extern void E_unit_set_duplicate_name
	PROTO_S ((CStringP, NStringP));
extern void E_unit_set_no_tld_name
	PROTO_S ((CStringP));
extern void E_capsule_bad_magic
	PROTO_S ((CapsuleP, NStringP, NStringP));
extern void E_capsule_bad_version
	PROTO_S ((CapsuleP, unsigned));
extern void E_capsule_version_mismatch
	PROTO_S ((CapsuleP, unsigned, unsigned));
extern void E_duplicate_unit_set_name
	PROTO_S ((CapsuleP, NStringP));
extern void E_out_of_order_unit_set_name
	PROTO_S ((CapsuleP, NStringP));
extern void E_unknown_unit_set_name
	PROTO_S ((CapsuleP, NStringP));
extern void E_duplicate_shape_name
	PROTO_S ((CapsuleP, NStringP));
extern void E_shape_and_name_count_mismatch
	PROTO_S ((CapsuleP, unsigned, unsigned));
extern void E_name_id_out_of_range
	PROTO_S ((CapsuleP, NStringP, NameKeyP, unsigned, unsigned));
extern void E_name_id_used_multiple_times
	PROTO_S ((CapsuleP, NStringP, NameKeyP, unsigned));
extern void E_too_many_tld_units
	PROTO_S ((CapsuleP));
extern void E_tld2_unit_set_type_obsolete
	PROTO_S ((CapsuleP));
extern void E_too_many_tld_unit_counts
	PROTO_S ((CapsuleP));
extern void E_too_many_tld_unit_mappings
	PROTO_S ((CapsuleP));
extern void E_tld_unit_wrong_size
	PROTO_S ((CapsuleP, unsigned, unsigned));
extern void E_unknown_tld_unit_type
	PROTO_S ((CapsuleP, unsigned));
extern void E_unit_set_count_mismatch
	PROTO_S ((CapsuleP, unsigned, unsigned));
extern void E_missing_tld_unit_set
	PROTO_S ((CStringP));
extern void E_extra_tld_unit_set
	PROTO_S ((CapsuleP));
extern void E_defined_but_not_declared
	PROTO_S ((CapsuleP, NStringP, NameKeyP));
extern void E_illegally_multiply_defined
	PROTO_S ((CapsuleP, NStringP, NameKeyP));
extern void E_bad_usage
	PROTO_S ((CapsuleP, NStringP, NameKeyP, unsigned));
extern void E_multiply_defined
	PROTO_S ((CapsuleP, NStringP, NameKeyP, CStringP));
extern void E_unit_count_num_mismatch
	PROTO_S ((CapsuleP, unsigned, unsigned, unsigned, NStringP));
extern void E_unit_mapping_num_mismatch
	PROTO_S ((CapsuleP, unsigned, unsigned, unsigned, NStringP));
extern void E_id_out_of_range
	PROTO_S ((CapsuleP, unsigned, unsigned, NStringP, unsigned, NStringP));
extern void E_too_many_library_files
	PROTO_S ((void));
extern void E_errf_null_char_in_builtin
	PROTO_S ((IStreamP));
extern void E_errf_null_character_in_name
	PROTO_S ((IStreamP));
extern void E_errf_null_character_in_string
	PROTO_S ((IStreamP));
extern void E_errf_newline_in_builtin
	PROTO_S ((IStreamP));
extern void E_errf_newline_in_name
	PROTO_S ((IStreamP));
extern void E_errf_newline_in_string
	PROTO_S ((IStreamP));
extern void E_errf_eof_in_builtin
	PROTO_S ((IStreamP));
extern void E_errf_eof_in_name
	PROTO_S ((IStreamP));
extern void E_errf_eof_in_string
	PROTO_S ((IStreamP));
extern void E_errf_illegal_esc_in_builtin
	PROTO_S ((IStreamP));
extern void E_errf_illegal_escape_in_name
	PROTO_S ((IStreamP));
extern void E_errf_illegal_escape_in_string
	PROTO_S ((IStreamP));
extern void E_errf_unknown_builtin
	PROTO_S ((IStreamP, CStringP));
extern void E_errf_illegal_character
	PROTO_S ((IStreamP, char));
extern void E_errf_expected_string
	PROTO_S ((IStreamP));
extern void E_errf_expected_section
	PROTO_S ((IStreamP));
extern void E_errf_unknown_string
	PROTO_S ((IStreamP, CStringP));
extern void E_errf_unknown_error
	PROTO_S ((IStreamP, CStringP));
extern void E_errf_illegal_message
	PROTO_S ((IStreamP, CStringP));
extern void E_errf_cannot_open
	PROTO_S ((CStringP));
extern void E_all_specified_with_capsules
	PROTO_S ((void));
extern void E_no_capsules_specified
	PROTO_S ((void));
extern void E_exception_unhandled
	PROTO_S ((ExceptionP, CStringP, unsigned));
extern void E_exception_corrupt_handler
	PROTO_S ((CStringP, unsigned));
extern void E_assertion_failed
	PROTO_S ((CStringP, CStringP, unsigned));
extern void E_dalloc_multi_deallocate
	PROTO_S ((GenericP, CStringP, unsigned, CStringP, unsigned));
extern void E_dalloc_corrupt_block
	PROTO_S ((GenericP, CStringP, unsigned));
extern void E_library_bad_magic
	PROTO_S ((LibraryP, NStringP, NStringP));
extern void E_library_bad_version
	PROTO_S ((LibraryP, unsigned));
extern void E_library_version_mismatch
	PROTO_S ((LibraryP, unsigned, unsigned));
extern void E_null_in_file_name
	PROTO_S ((LibraryP, NStringP));
extern void E_capsule_not_found
	PROTO_S ((CStringP, CStringP));
extern void E_extracting_capsule
	PROTO_S ((CStringP, CStringP));
extern void E_lib_unknown_type
	PROTO_S ((LibraryP, unsigned));
extern void E_lib_defined_but_not_declared
	PROTO_S ((LibraryP, NStringP, NameKeyP));
extern void E_lib_illegally_mult_defined
	PROTO_S ((LibraryP, NStringP, NameKeyP));
extern void E_lib_bad_usage
	PROTO_S ((LibraryP, NStringP, NameKeyP, unsigned));
extern void E_lib_multiply_defined
	PROTO_S ((LibraryP, NStringP, NameKeyP, LibCapsuleP));
extern void E_capsule_index_too_big
	PROTO_S ((LibraryP, NStringP, NameKeyP, unsigned, unsigned));
extern void E_cannot_hide_shape
	PROTO_S ((NStringP));
extern void E_cannot_hide
	PROTO_S ((NStringP, NameKeyP));
extern void E_cannot_hide_undefined
	PROTO_S ((NStringP, NameKeyP));
extern void E_cannot_keep_shape
	PROTO_S ((NStringP));
extern void E_cannot_keep
	PROTO_S ((NStringP, NameKeyP));
extern void E_bad_mode
	PROTO_S ((char));
extern void E_missing_files
	PROTO_S ((void));
extern void E_no_memory
	PROTO_S ((void));
extern void E_read_error
	PROTO_S ((CStringP));
extern void E_write_error
	PROTO_S ((CStringP));
extern void E_cannot_open_input_file
	PROTO_S ((CStringP));
extern void E_cannot_open_output_file
	PROTO_S ((CStringP));
extern void E_cannot_open_library_file
	PROTO_S ((CStringP));
extern void E_illegal_external_name
	PROTO_S ((CStringP));
extern void E_no_single_definition
	PROTO_S ((NStringP, NameKeyP));
extern void E_rename_cycle
	PROTO_S ((NStringP, NameKeyP));
extern void E_no_definition_found
	PROTO_S ((NStringP, NameKeyP));
extern void E_cannot_open_rename_file
	PROTO_S ((CStringP));
extern void E_rename_expected_shape
	PROTO_S ((IStreamP));
extern void E_rename_expected_name
	PROTO_S ((IStreamP));
extern void E_rename_expected_semi
	PROTO_S ((IStreamP));
extern void E_rename_unexpected_eof
	PROTO_S ((IStreamP));
extern void E_rename_unexpected_newline
	PROTO_S ((IStreamP));
extern void E_rename_illegal_escape
	PROTO_S ((IStreamP));
extern void E_rename_illegal_char
	PROTO_S ((IStreamP, char));
extern void E_too_many_ids
	PROTO_S ((void));
extern void E_unexpected_eof_in_tdf
	PROTO_S ((TDFReaderP));
extern void E_tdf_integer_too_big_in_tdf
	PROTO_S ((TDFReaderP));
extern void E_unsupported_char_size_in_tdf
	PROTO_S ((TDFReaderP, unsigned));
extern void E_bad_name_type_in_tdf
	PROTO_S ((TDFReaderP, unsigned));
extern void E_expected_eof_in_tdf
	PROTO_S ((TDFReaderP));

extern void gen_errors_init_errors
	PROTO_S ((void));
