#!/bin/sh

BASE=/u/g/release/Source
SRC=${BASE}/src/tools/tnc
SPEC=${BASE}/src/lib/tdf/def_4_1.db

make_mf\
    +A BASE=${BASE}\
    +A SRC=${SRC}\
    +A SRC1=${SRC}/templ\
    +A SPEC=${SPEC}\
    +W ...\
    +V 'EXTRA=auto'\
    -o .../tnc\
    -Yansi -Xs\
    ${SRC}/*.c\
    > Makefile

cat >> Makefile << EOF

MAKE_TDF=make_tdf

auto : \${SRC}/tdf.c \${SRC}/tdf.h \${SRC}/check_exp.h

\${SRC}/tdf.c : \${SPEC} \${SRC1}/tdf.c
	@\${REMOVE} \${SRC}/tdf.c
	\${MAKE_TDF} \${SPEC} \${SRC1}/tdf.c \${SRC}/tdf.c

\${SRC}/tdf.h : \${SPEC} \${SRC1}/tdf.h
	@\${REMOVE} \${SRC}/tdf.h
	\${MAKE_TDF} \${SPEC} \${SRC1}/tdf.h \${SRC}/tdf.h

\${SRC}/check_exp.h : \${SPEC} \${SRC1}/check_exp.h
	@\${REMOVE} \${SRC}/check_exp.h
	\${MAKE_TDF} \${SPEC} \${SRC1}/check_exp.h \${SRC}/check_exp.h

auto_clobber :
	\${REMOVE} \${SRC}/tdf.c \${SRC}/tdf.h \${SRC}/check_exp.h
EOF
