# $TenDRA: Makefile 1610 2004-03-07 17:04:15Z verm $

PDF_TITLE=	TenDRA tcc manpage
PDF_SUBJECT=	TenDRA tcc manpage

DOC?= refentry

SRCS=   refentry.xml

.include "../Makefile.inc"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
