# $TenDRA$
#
#

DOC_PREFIX?=../

SUBDIR=	calculus \
	diag \
	faq \
	guide \
	pl \
	port \
	share \
	sid \
	tcc \
	tcpplus \
	tdf \
	tdfc \
	tld \
	tnc \
	tspec


.include "${DOC_PREFIX}/share/mk/doc.project.mk"
