# $TenDRA$
#
#

DOC_PREFIX?=../

# SGML documents.
SUBDIR=		calculus changes contributors diag faq guide \
		make pl port readme reference register \
		release sid tcc tcpplus tdf tdfc team \
		tld tnc tspec

# mdoc conversion, misc documents and the manpages
SUBDIR+=	mdoc misc manpages


.include "${DOC_PREFIX}/share/mk/doc.project.mk"



