# $Id$

.include "Makefile.inc"


ENVFILE+=	default
ENVFILE+=	system
ENVFILE+=	system+
ENVFILE+=	building

ENVFILE+=	c
ENVFILE+=	c++
ENVFILE+=	iso
ENVFILE+=	ansi

ENVFILE+=	aes
ENVFILE+=	cose
ENVFILE+=	posix
ENVFILE+=	posix1
ENVFILE+=	posix2
ENVFILE+=	strict_posix
ENVFILE+=	strict_svid3
ENVFILE+=	strict_xpg3
ENVFILE+=	svid3
ENVFILE+=	unix95
ENVFILE+=	xpg3
ENVFILE+=	xpg4

ENVFILE+=	x5_aw
ENVFILE+=	x5_ext
ENVFILE+=	x5_lib
ENVFILE+=	x5_mit
ENVFILE+=	x5_mu
ENVFILE+=	x5_private
ENVFILE+=	x5_proto
ENVFILE+=	x5_t
ENVFILE+=	motif_1_1
ENVFILE+=	motif_1_2
ENVFILE+=	strict_mot_1_2

ENVFILE+=	Goption
ENVFILE+=	K-PIC
ENVFILE+=	K-ieee
ENVFILE+=	K-noieee
ENVFILE+=	K-prom
ENVFILE+=	alloca
ENVFILE+=	bsd_extn
ENVFILE+=	gcc
ENVFILE+=	motif_private
ENVFILE+=	mse
ENVFILE+=	target_tok
ENVFILE+=	tdf_ext

.include <tendra.env.mk>

