# $Id$

.include "Makefile.inc"


ENVFILE+=	default
ENVFILE+=	system
ENVFILE+=	building

ENVFILE+=	c
ENVFILE+=	c++

ENVFILE+=	Goption
ENVFILE+=	K-PIC
ENVFILE+=	K-ieee
ENVFILE+=	K-noieee
ENVFILE+=	K-prom
ENVFILE+=	target_tok
ENVFILE+=	tdf_ext

.include <tendra.env.mk>

