# $TenDRA$

PDF_TITLE=	tspec API Specification Tool
PDF_SUBJECT=	tspec API Specification Tool

DOC?= book

SRCS=   book.xml

.include "../Makefile.inc"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
