# $Id$

.include "Makefile.inc"


CCOPTS+=	-I ..
CCOPTS+=	-I .

SRCS+=	dwarf_info.c
SRCS+=	dwarf_loc.c
SRCS+=	dwarf_out.c
SRCS+=	dwarf_proc.c
SRCS+=	dwarf_queue.c
SRCS+=	dwarf_type.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

