# $Id$

.include "Makefile.inc"


CCOPTS+=	-I ..
CCOPTS+=	-I .

SRCS+=	dw1_info.c
SRCS+=	dw1_loc.c
SRCS+=	dw1_out.c
SRCS+=	dw1_proc.c
SRCS+=	dw1_queue.c
SRCS+=	dw1_type.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

