# $Id$

all:
	cd diagnostic && $(MAKE) all
	cd guide && $(MAKE) all
	# cd register && $(MAKE) all
	# cd specification && $(MAKE) all

clean:
	cd diagnostic && $(MAKE) clean
	cd guide && $(MAKE) clean
	# cd register && $(MAKE) clean
	# cd specification && $(MAKE) clean

