# $TenDRA$

PDF_TITLE=	TenDRA make_tdf manpage
PDF_SUBJECT=	TenDRA make_tdf manpage

DOC?= refentry

SRCS=   refentry.sgml

.include "../Makefile.inc"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
