# $TenDRA: Makefile 2004 2004-08-27 05:55:14Z chopra $

PDF_TITLE=	TenDRA make_tdf manpage
PDF_SUBJECT=	TenDRA make_tdf manpage

DOC?= refentry

SRCS=   refentry.xml

.include "../Makefile.inc"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
