# $TenDRA$

PDF_TITLE=	TenDRA ppc601 (power) aix Installer Manpage
PDF_SUBJECT=	TenDRA ppc601 (power) aix  Installer Manpage

DOC?=	refentry

SRCS=	refentry.sgml

# en/manpages/trans
.include "../Makefile.inc"

# en/
.include "../../../Makefile.inc"

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
