# $Id$

SRCS=	baseinfo.cc cmath.cc cstring.cc cwchar.cc exception.cc new.cc new1.cc \
	new2.cc new3.cc new4.cc new5.cc new6.cc new7.cc new8.cc pure.cc \
	term.cc typeinfo.cc what.cc

.include "Makefile.inc"


LIB=	cpp

.include <tendra.lib.mk>

