# $Id$

.include "Makefile.inc"


ENVFILE+=	default

ENVFILE+=	K-i386
ENVFILE+=	K-i486
ENVFILE+=	K-P5

ENVFILE+=	K-frame
ENVFILE+=	K-noframe

ENVFILE+=	K-PIC

ENVFILE+=	tcc_prof

.include <tendra.env.mk>

