# $Id$

.include "Makefile.inc"


DOC=       	${.CURDIR:T}
DOC_PREFIX=	${.CURDIR:H:T}
DOC_DPADD+= \
	bitencoding.xml        \
	constructs.xml         \
	describing.xml         \
	installerbehaviour.xml \
	introduction.xml       \
	notes.xml              \
	preface.xml            \
	structure.xml          \
	supplementary.xml

.include <tendra.doc.mk>
