#!/bin/sh

# $Id$
#
# Copyright (c) 2002-2005 The TenDRA Project <http://www.tendra.org/>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of The TenDRA Project nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific, prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

# This script is inspired by Postfix' makedefs script.
# The purpose of this script is to determine the host on which we are
# compiling TenDRA and provide sane compilation defaults.

HOSTARCH=`/usr/bin/env uname -m`
SYSTEM=`/usr/bin/env uname -s`
VERSION=`/usr/bin/env uname -r`

if [ "${1}" = "-h" ]; then
	echo "makedefs"
	echo "usage: [OPTIONS] ./makedefs [-h]"
	echo
	echo "Configuration definition generator of the TenDRA Project"
	echo
	echo "Available OPTIONS (OPTION=value):"
	echo "PREFIX		installation prefix"
	echo "CC		C compiler"
	echo "CFLAGS		C compiler flags"
	echo "LDFLAGS		linker flags"
	echo "EXECFORMAT	desired default executable format (aout, elf)"
	exit 1
fi

if [ -f Makefile.defs ]; then
	echo "NOTICE: old Makefile.defs file found, overwriting..."
	echo
fi

echo "${SYSTEM}.${VERSION} detected..."
echo

# Set up defaults
if [ -z "${PREFIX}" ]; then
	PREFIX=/usr/local;
fi

if [ -z "${CC}" ]; then
	CC=cc
fi

if [ -z "${EXECFORMAT}" ]; then
	EXECFORMAT=elf
fi

case "${SYSTEM}.${VERSION}" in
	DragonFly.1*)
			# System definition is __DragonFly__
			OSFAM="dragonfly"
			OSVER="DRAGONFLY1"
			;;
	FreeBSD.4*)
			# System definition is __FreeBSD__
			OSFAM="freebsd"
			OSVER="FREEBSD4"
			;;
	FreeBSD.5*)
			# System definition is __FreeBSD__
			OSFAM="freebsd"
			OSVER="FREEBSD5"
			;;
	FreeBSD.6*)
			# System definition is __FreeBSD__
			OSFAM="freebsd"
			OSVER="FREEBSD6"
			;;
	FreeBSD.7*)
			# System definition is __FreeBSD__
			OSFAM="freebsd"
			OSVER="FREEBSD7"
			;;
	Linux.2.4*)
			# System definition is __linux
			OSFAM="linux"
			OSVER="LINUX24"
			;;
	Linux.2.6*)
			# System definition is __linux
			OSFAM="linux"
			OSVER="LINUX26"
			;;
	NetBSD.1*)
			#
			OSFAM="netbsd"
			OSVER="NETBSD1"
			;;
	NetBSD.2*)
			#
			OSFAM="netbsd"
			OSVER="NETBSD2"
			;;
	NetBSD.3*)
			#
			OSFAM="netbsd"
			OSVER="NETBSD3"
			;;
	NetBSD.4*)
			#
			OSFAM="netbsd"
			OSVER="NETBSD4"
			;;
	OpenBSD.3*)
			#
			OSFAM="openbsd"
			OSVER="OPENBSD3"
			;;
	OpenBSD.4*)
			#
			OSFAM="openbsd"
			OSVER="OPENBSD4"
			;;
	SunOS.5*)
			OSFAM="solaris"
			OSVER="SUNOS5"
			;;
	*)
			# Make sure we specify what we want to hear from the
			# people submitting feedback.
			echo "Unknown \"${SYSTEM}\" and \"${VERSION}\" combination"
			echo "Please report the following to the developers:"
			echo
			echo "uname -r:	${VERSION}"
			echo "uname -s:	${SYSTEM}"
			echo
			;;
esac

case "$HOSTARCH" in
	alpha)
			# DEC, nay, Compaq, nay HP Alpha
			BLDARCH="alpha"
			BLDARCHBITS="64"
			;;
	amd64|x86_64)
			# AMD64
			BLDARCH="amd64"
			BLDARCHBITS="64"
			;;
	i?86|i86pc)
			# Intel 80386 and friends
			BLDARCH="80x86"
			BLDARCHBITS="32"
			;;
	sparc)
			# SPARC 32 bit
			BLDARCH="sparc"
			BLDARCHBITS="32"
			;;
	sparc64)
			# SPARC 64 bit
			BLDARCH="sparc"
			BLDARCHBITS="64"
			;;
	*)
			echo "Unknown architecture \"${HOSTARCH}\""
			echo "Please report the following to the developers:"
			echo
			echo "uname -m:	${HOSTARCH}"
			echo
			;;
esac

echo "Setting Makefile.defs environment to the following:"
echo
echo "PREFIX:		${PREFIX}"
echo "CC:		${CC}"
echo "CFLAGS:		${CFLAGS}"
echo "LDFLAGS:	${LDFLAGS}"
echo "OSFAM:		${OSFAM}"
echo "OSVER:		${OSVER}"
echo "BLDARCH:	${BLDARCH} (${HOSTARCH})"
echo "BLDARCHBITS:	${BLDARCHBITS} bit"
echo "EXECFORMAT:	${EXECFORMAT}"

cat > Makefile.defs <<EOF
PREFIX?=${PREFIX}
CC?=${CC}
CFLAGS=${CFLAGS}
LDFLAGS=${LDFLAGS}
OSFAM=${OSFAM}
OSVER=${OSVER}
BLDARCH=${BLDARCH}
BLDARCHBITS=${BLDARCHBITS}
EXECFORMAT=${EXECFORMAT}
EOF
