# $TenDRA$

.PATH : ${.CURDIR} ${.CURDIR}/../../../common

DATA=	K-P5 K-PIC K-frame K-i386 K-i486 K-noframe \
	Z-p Z-p1 Z-p2 Z-p4 default.extra tcc_diag tcc_prof \
	default.extra

.include "../../../Makefile.inc"
.include "../../../../../../mk/base/tendra.prog.mk"
