# $Id$

# Standard directories and files
SRCX= ${.CURDIR}/../shared

CC?= 		tcc
TCCOPTS=	-Ysystem
CCOPTS=		${TCCOPTS} -I${SRCX}
LIBS=

PROG=		tuname

SRCS=		tuname.c

# Dependencies and construction rules

.include "../Makefile.inc"
