# $TenDRA$

.include "../Makefile.inc"

.PATH :	${.CURDIR}/images

IMAGES_OBJ?=	class.obj classa.obj classb.obj classc.obj classd.obj \
		compile.obj diamond.obj graph.obj rttid.obj try.obj \
		virtualb.obj virtualc.obj virtuald.obj

DOC?= book

SRCS=   book.sgml

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
