# $TenDRA$

.PATH :	${.CURDIR}/images

PDF_TITLE=	C++ Producer Guide
PDF_SUBJECT=	C++ Producer Guide

IMAGES_OBJ?=	class.obj classa.obj classb.obj classc.obj classd.obj \
		compile.obj diamond.obj graph.obj rttid.obj try.obj \
		virtualb.obj virtualc.obj virtuald.obj

DOC?= book

SRCS=   book.sgml

.include "../Makefile.inc"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
