# $TenDRA$

PROG=	trans

# installers/80x86/freebsd
SRCS=	assembler.c diag_out.c machine.c

# installers/80x86
.include "${.CURDIR}/../Makefile.inc"

# installers/
.include "${.CURDIR}/../../Makefile.inc"

.include "${.CURDIR}/../../../../mk/base/tendra.prog.mk"
