.include "Makefile.inc"


# TODO: perhaps an extra-params variable, for:
#    <xsl:param name="css.decoration">0</xsl:param>
#    <xsl:param name="paper.type">A4</xsl:param>
#    <xsl:param name="section.autolabel">1</xsl:param>
#    <xsl:param name="section.label.includes.component.label">1</xsl:param>

DOC=	${.CURDIR:T}

.include <tendra.doc.mk>

