# $Id$

DOC=	lexi

.if exists(../share)
# building standalone
# TODO override STYLEDIR here
.include "../share/doc.docbook.mk"
.else
# building within tendra-doc
.include "../../../share/doc.docbook.mk"
.endif

