.\" 		 Crown Copyright (c) 1997
.\" 
.\" This TenDRA(r) Manual Page is subject to Copyright
.\" owned by the United Kingdom Secretary of State for Defence
.\" acting through the Defence Evaluation and Research Agency
.\" (DERA).  It is made available to Recipients with a
.\" royalty-free licence for its use, reproduction, transfer
.\" to other parties and amendment for any purpose not excluding
.\" product development provided that any such use et cetera
.\" shall be deemed to be acceptance of the following conditions:-
.\" 
.\"     (1) Its Recipients shall ensure that this Notice is
.\"     reproduced upon any copies or amended versions of it;
.\" 
.\"     (2) Any amended version of it shall be clearly marked to
.\"     show both the nature of and the organisation responsible
.\"     for the relevant amendment or amendments;
.\" 
.\"     (3) Its onward transfer from a recipient to another
.\"     party shall be deemed to be that party's acceptance of
.\"     these conditions;
.\" 
.\"     (4) DERA gives no warranty or assurance as to its
.\"     quality or suitability for any purpose and DERA accepts
.\"     no liability whatsoever in relation to any use to which
.\"     it may be put.
.\"
.TH pl 1
.SH NAME
pl \- PL_TDF compiler producing TDF
.SH SYNOPSIS
\fBpl\fR [\fI-v\fR] [\fI-I path\fR]* [\fI-V\fR] \fIinfile.pl\fR \fIoutfile.j\fR
.\" ----------------------------------------------------------------------
.SH DESCRIPTION
The action of \fBpl\fR is to compile a PL_TDF text in \fIinfile.pl\fR
to a TDF capsule in \fIoutfile.j\fR. (See \fIPL_TDF Definition\fR). The
resulting .j file is suitable for linking and translation by \fItcc(1)\fR. 
.\" ----------------------------------------------------------------------
.SH OPTIONS
.\" ----------------------------------------------------------------------
.IP \fB-v\fR
This option produces a "pretty print" of the TDF capsule on the standard 
output.
.\" ----------------------------------------------------------------------
.IP \fB-I\ path\fR
Gives the search path for any #include files in the PL_TDF text.
.\" ----------------------------------------------------------------------
.IP \fB-V\fR
This option causes \fBpl\fR to print its version number and the
version of the TDF specification it supports.
.\" ----------------------------------------------------------------------
.SH SEE ALSO
\fItcc\fR(1).
