# $Id$

.include "Makefile.inc"


TSPEC=	${OBJ_DIR}/src/tspec

#TSPEC_FLAGS+=	-a

APIS+=	ansi
APIS+=	iso
APIS+=	posix
APIS+=	posix1
APIS+=	posix2
#APIS+=	posix3
APIS+=	unix95
APIS+=	xpg3
APIS+=	xpg4
APIS+=	svid3

.include <tendra.tspec.mk>

