# $Id$

.include "Makefile.inc"


TSPEC=	${OBJ_DIR}/src/tspec

#TSPEC_FLAGS+=	-a

APIS+=	c/c89
APIS+=	c/c89-fs
APIS+=	c/c90
APIS+=	posix
APIS+=	posix1
APIS+=	posix2
APIS+=	unix95
APIS+=	xpg3
APIS+=	xpg4
APIS+=	svid/svid3

.include <tendra.tspec.mk>

