# $Id$

.include "Makefile.inc"


TSPEC=	${OBJ_DIR}/src/tspec

#TSPEC_FLAGS+=	-a

APIS+=	c/c89
APIS+=	c/c89-fs
APIS+=	c/c90

APIS+=	svid/svid3

APIS+=	posix/posix
APIS+=	posix/posix1
APIS+=	posix/posix2

APIS+=	cae/xpg3

APIS+=	cae/acse-xap
APIS+=	cae/dtp-xa

APIS+=	cae/xsh4-base
APIS+=	cae/xsh4-clb
APIS+=	cae/xsh4-crypt
APIS+=	cae/xsh4-i18n
APIS+=	cae/xsh4-shm

APIS+=	cae/xsh4v2-base
APIS+=	cae/xsh4v2-clb
APIS+=	cae/xsh4v2-crypt
APIS+=	cae/xsh4v2-i18n
APIS+=	cae/xsh4v2-shm
APIS+=	cae/xsh4v2-unix

APIS+=	cae/xcurses4v2

APIS+=	cae/xsh5
APIS+=	cae/xns5-ar
APIS+=	cae/xns5-socket
APIS+=	cae/xns5-xti

.include <tendra.tspec.mk>

