/*
    		 Crown Copyright (c) 1997
    
    This TenDRA(r) Computer Program is subject to Copyright
    owned by the United Kingdom Secretary of State for Defence
    acting through the Defence Evaluation and Research Agency
    (DERA).  It is made available to Recipients with a
    royalty-free licence for its use, reproduction, transfer
    to other parties and amendment for any purpose not excluding
    product development provided that any such use et cetera
    shall be deemed to be acceptance of the following conditions:-
    
        (1) Its Recipients shall ensure that this Notice is
        reproduced upon any copies or amended versions of it;
    
        (2) Any amended version of it shall be clearly marked to
        show both the nature of and the organisation responsible
        for the relevant amendment or amendments;
    
        (3) Its onward transfer from a recipient to another
        party shall be deemed to be that party's acceptance of
        these conditions;
    
        (4) DERA gives no warranty or assurance as to its
        quality or suitability for any purpose and DERA accepts
        no liability whatsoever in relation to any use to which
        it may be put.
*/

/*
    AUTOMATICALLY GENERATED BY lexi VERSION 1.1
*/


/* KEYWORDS */

MAKE_KEYWORD ( "+BASE_API", lex_base_Hapi ) ;
MAKE_KEYWORD ( "+CONST", lex_constant ) ;
MAKE_KEYWORD ( "+DEFINE", lex_define ) ;
MAKE_KEYWORD ( "+ELSE", lex_else ) ;
MAKE_KEYWORD ( "+ENDIF", lex_endif ) ;
MAKE_KEYWORD ( "+ENUM", lex_enumerate ) ;
MAKE_KEYWORD ( "+EXP", lex_exp ) ;
MAKE_KEYWORD ( "+FIELD", lex_field ) ;
MAKE_KEYWORD ( "+FUNC", lex_func ) ;
MAKE_KEYWORD ( "+IF", lex_if ) ;
MAKE_KEYWORD ( "+IFDEF", lex_ifdef ) ;
MAKE_KEYWORD ( "+IFNDEF", lex_ifndef ) ;
MAKE_KEYWORD ( "+IMPLEMENT", lex_implement ) ;
MAKE_KEYWORD ( "+INFO", lex_info ) ;
MAKE_KEYWORD ( "+MACRO", lex_macro ) ;
MAKE_KEYWORD ( "+NAT", lex_nat ) ;
MAKE_KEYWORD ( "+SET", lex_set ) ;
MAKE_KEYWORD ( "+STATEMENT", lex_statement ) ;
MAKE_KEYWORD ( "+SUBSET", lex_subset ) ;
MAKE_KEYWORD ( "+TOKEN", lex_token ) ;
MAKE_KEYWORD ( "+TYPE", lex_type ) ;
MAKE_KEYWORD ( "+TYPEDEF", lex_typedef ) ;
MAKE_KEYWORD ( "+USE", lex_use ) ;
MAKE_KEYWORD ( "arith", lex_arith ) ;
MAKE_KEYWORD ( "char", lex_char ) ;
MAKE_KEYWORD ( "const", lex_const ) ;
MAKE_KEYWORD ( "double", lex_double ) ;
MAKE_KEYWORD ( "enum", lex_enum ) ;
MAKE_KEYWORD ( "extern", lex_extern ) ;
MAKE_KEYWORD ( "float", lex_float ) ;
MAKE_KEYWORD ( "int", lex_int ) ;
MAKE_KEYWORD ( "long", lex_long ) ;
MAKE_KEYWORD ( "lvalue", lex_lvalue ) ;
MAKE_KEYWORD ( "scalar", lex_scalar ) ;
MAKE_KEYWORD ( "short", lex_short ) ;
MAKE_KEYWORD ( "signed", lex_signed ) ;
MAKE_KEYWORD ( "struct", lex_struct ) ;
MAKE_KEYWORD ( "union", lex_union ) ;
MAKE_KEYWORD ( "unsigned", lex_unsigned ) ;
MAKE_KEYWORD ( "void", lex_void ) ;
MAKE_KEYWORD ( "volatile", lex_volatile ) ;
MAKE_KEYWORD ( "weak", lex_weak ) ;
MAKE_KEYWORD ( "~building_libs", lex_building ) ;
MAKE_KEYWORD ( "~promote", lex_promote ) ;
MAKE_KEYWORD ( "~protect", lex_protect ) ;
MAKE_KEYWORD ( "~special", lex_special ) ;
