/*
 * Copyright 2002-2011, The TenDRA Project.
 * Copyright 1997, United Kingdom Secretary of State for Defence.
 *
 * See doc/copyright/ for the full copyright terms.
 */

    
    
    
    
    

#ifndef LOC_EXT_INCLUDED
#define LOC_EXT_INCLUDED


/*
    LOCATION CONSTRUCTS

    These macros give some alternative constructs for creating location
    structures.  This file is automatically generated from algebra
    %X (version %V) by %ZX (version %ZV).
*/

#define CREATE_loc(A, B, C, D, E, F, P)\
    {\
	LOCATION *loc_ = &(P);\
	loc_->line = 1;\
	loc_->column = 0;\
	loc_->posn = MAKE_ptr(SIZE_posn);\
	MAKE_posn((A), (B), (C), (D), 0, (E), (F), loc_->posn);\
    }

#define NULL_loc	{ 0, 0, NULL_ptr (POSITION) }


#endif
