# $Id$

.include "Makefile.inc"


CCOPTS+=	-I ../../common

SRCS+=	68k_globals.c
SRCS+=	assembler.c
SRCS+=	codec.c
SRCS+=	coder.c
SRCS+=	codex.c
SRCS+=	evaluate.c
SRCS+=	general_proc.c
SRCS+=	glopt.c
SRCS+=	inliner.c
#SRCS+=	input.c
SRCS+=	instr.c
SRCS+=	localflags.c
SRCS+=	mach_ins.c
SRCS+=	mach_op.c
SRCS+=	main.c
SRCS+=	ops_float.c
SRCS+=	ops_int.c
SRCS+=	ops_logic.c
SRCS+=	ops_misc.c
SRCS+=	output.c
SRCS+=	peephole.c
SRCS+=	scan2.c
SRCS+=	spec_tok.c
SRCS+=	special_exps.c
SRCS+=	stab_types.c
SRCS+=	tests.c
SRCS+=	trans.c
SRCS+=	utility.c
SRCS+=	weights.c
SRCS+=	where.c
SRCS+=	xdb_basics.c
SRCS+=	xdb_output.c
SRCS+=	xdb_types.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

