# TenDRA make build infrastructure
#
# $Id$

.if !defined(_TENDRA_WORK_API_MK_)
_TENDRA_WORK_API_MK_=1

.include <tendra.base.mk>
.include <tendra.functions.mk>

.if !defined(API)
.BEGIN:
	@${ECHO} '$${API} must be set'
	@${EXIT} 1;
.endif



#
# Build API
#

_REALWORK: api-depend
	@cd ${BASE_DIR}/${APIS}/${API}/ && ${.MAKE} makeapi ${.MAKEFLAGS}

JOPTS= -Y32bit -I${BASE_DIR}/src/lib/machines/${OSFAM}/${BLDARCH}/include \
	-I/usr/include -f${BASE_DIR}/${STARTUP_MACH}/${API}.h -D__BUILDING_LIBS

api-depend:
	@${ECHO} "==> Creating API source for ${API}"
	${TSPEC} -v -I${BASE_DIR}/${APIS} -O. -S./building ${API}

# Include Makefile generated by tspec during api-depend.
.if exists(./building/${API}.api/Makefile)
.include "./building/${API}.api/Makefile"
.endif

# XXX: where does APILIB come from?
makeapi: ${APILIB}

${APILIB}: ${APIOBJS}
	@${ECHO} "==> Linking ${API} API"
	${TLD} -mc -o ${APILIB} ${APIOBJS}

CLEAN_EXTRA+= ${APILIB} ${APIOBJS} ${APIOBJS:S/.j/.c/} \
              ./building/${API}.api/Makefile

_objdir=	${OBJ_DIR}/${APIS}



#
# Install API.
#

# Relative to .OBJDIR.
CAPIDIR=${.OBJDIR}/building
SAPIDIR=${.OBJDIR}/shared
HAPIDIR=${.OBJDIR}

# Absolute target dirs.
SINSTDIR=${INSTALL_DIR}/lib/include/shared
HINSTDIR=${INSTALL_DIR}/lib/include
CINSTDIR=${INSTALL_DIR}/lib/building
LINSTDIR=${INSTALL_DIR}/lib

_REALINSTALL: .USE
	@${ECHO} "==> Installing ${API} API"
	${CONDCREATE} "${HINSTDIR}" "${CINSTDIR}" "${LINSTDIR}"
.if exists(${SAPIDIR}/${API}.api)
	${CONDCREATE} "${SINSTDIR}"
.endif
	${INSTALL} -m 644 ${.OBJDIR}/${API}.tl ${LINSTDIR}
	@cd ${CAPIDIR} && ${FIND} ${API}.api -name '.*' -prune -o -print | \
	while read file; do \
		if ${TEST} -d $${file}; then \
			${ECHO} ${INSTALL} -m 755 -d ${CINSTDIR}/$${file}; \
			${INSTALL} -m 755 -d ${CINSTDIR}/$${file} || ${EXIT} $$?; \
		else \
			${ECHO} ${INSTALL} -m 644 $${file} ${CINSTDIR}/$${file}; \
			${INSTALL} -m 644 $${file} ${CINSTDIR}/$${file} || ${EXIT} $$?; \
		fi; \
	done
	@cd ${HAPIDIR} && ${FIND} ${API}.api -name '.*' -prune -o -print | \
	while read file; do \
		if ${TEST} -d $${file}; then \
			${ECHO} ${INSTALL} -m 755 -d ${HINSTDIR}/$${file}; \
			${INSTALL} -m 755 -d ${HINSTDIR}/$${file} || ${EXIT} $$?; \
		else \
			${ECHO} ${INSTALL} -m 644 $${file} ${HINSTDIR}/$${file}; \
			${INSTALL} -m 644 $${file} ${HINSTDIR}/$${file} || ${EXIT} $$?; \
		fi; \
	done
.if exists(${SAPIDIR}/${API}.api)
	@cd ${SAPIDIR} && ${FIND} ${API}.api -name '.*' -prune -o -print | \
	while read file; do \
		if ${TEST} -d $${file}; then \
			${ECHO} ${INSTALL} -m 755 -d ${SINSTDIR}/$${file}; \
			${INSTALL} -m 755 -d ${SINSTDIR}/$${file} || ${EXIT} $$?; \
		else \
			${ECHO} ${INSTALL} -m 644 $${file} ${SINSTDIR}/$${file}; \
			${INSTALL} -m 644 $${file} ${SINSTDIR}/$${file} || ${EXIT} $$?; \
		fi; \
	done
.endif



.endif	# !defined(_TENDRA_WORK_API_MK_)
