# $Id$

.include "Makefile.inc"


SRCS+=	action.c
SRCS+=	basic.c
SRCS+=	cstring-list.c
SRCS+=	entry-list.c
SRCS+=	entry.c
SRCS+=	key.c
SRCS+=	alt.c
SRCS+=	name.c
SRCS+=	non-local.c
SRCS+=	rstack.c
SRCS+=	scope.c
SRCS+=	table.c
SRCS+=	type.c
SRCS+=	types.c
SRCS+=	rule.c
SRCS+=	item.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

