# $Id$

.include "Makefile.inc"


CCOPTS+=	-I ../diag
CCOPTS+=	-I ../linkinfo
CCOPTS+=	-I ../reader
CCOPTS+=	-I .

SRCS+=	aldefs.c
SRCS+=	case_opt.c
SRCS+=	refactor.c
SRCS+=	refactor_id.c
SRCS+=	refactor_ext.c
SRCS+=	complex_eq.c
SRCS+=	const.c
SRCS+=	exp.c
SRCS+=	f64.c
SRCS+=	flags.c
SRCS+=	flpt.c
SRCS+=	flpt_fns.c
SRCS+=	foralls.c
SRCS+=	global_opt.c
SRCS+=	inl_norm.c
SRCS+=	inline.c
SRCS+=	install_fns.c
SRCS+=	installglob.c
SRCS+=	label_ops.c
SRCS+=	me_fns.c
SRCS+=	misc_c.c
SRCS+=	unroll.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

