# $TenDRA$

SRCDIRS+=	power/common

# installers/power/common
SRCS+=	ash.c codehere.c comment.c diagout.c dynamic_init.c error.c eval.c \
	frames.c getregs.c glopt.c guard.c inlinechoice.c inst_fmt.c instruct.c \
	is_worth.c labels.c locate.c machine.c machine_toks.c macro.c \
	makecode.c mask.c mem_copy.c move.c muldvrem.c needscan.c oprators.c \
	parameter.c pp.c proc.c record_bit.c regable.c regalloc.c regexps.c \
	spec.c spec_tok.c stack.c tempdecs.c translat.c weights.c

