# $Id$

.include "Makefile.inc"


HEADERS+= ansi.h
HEADERS+= iso.h
HEADERS+= posix1.h
HEADERS+= posix2.h
HEADERS+= posix.h
HEADERS+= svid3.h
HEADERS+= unix95.h
HEADERS+= xpg3.h
HEADERS+= xpg4.h

.include <tendra.feature.mk>

