# $Id$

.include "Makefile.inc"


HEADERS+= c89.h
HEADERS+= c90.h
HEADERS+= posix1.h
HEADERS+= posix2.h
HEADERS+= posix.h
HEADERS+= svid3.h
HEADERS+= unix95.h
HEADERS+= xpg3.h
HEADERS+= xpg4.h

.include <tendra.feature.mk>

