# $Id$

.include "Makefile.inc"


HEADERS+= c89.h
HEADERS+= c95.h

HEADERS+= posix.h
HEADERS+= posix1.h
HEADERS+= posix2.h

HEADERS+= svid3.h

HEADERS+= xpg3.h
HEADERS+= xns4.h
HEADERS+= xsh4.h
HEADERS+= xcurses4v2.h
HEADERS+= xsh4v2.h
HEADERS+= xns5.h
HEADERS+= xsh5.h

.include <tendra.feature.mk>

