# $Id$

.include "Makefile.inc"


ENVSTANDALONE=

ENVFILE+=	ansi
ENVFILE+=	iso

ENVFILE+=	cose
ENVFILE+=	xsh4
ENVFILE+=	xpg3
ENVFILE+=	xpg4

ENVFILE+=	strict_posix
ENVFILE+=	strict_svid3
ENVFILE+=	strict_xpg3
ENVFILE+=	strict_mot_1_2

ENVFILE+=	alloca
ENVFILE+=	motif_private

ENVFILE+=	x5_proto
ENVFILE+=	x5_private

PREFIX_ENV:=	${PREFIX_TSPEC}/TenDRA/env

.include <tendra.env.mk>

