# $Id$

.include "Makefile.inc"

.include <tendra.base.mk>
.include <tendra.makedefs.mk>


ENVFILE+=	default

ENVCOMMON+=	machines/common/env
ENVCOMMON+=	arch/${BLDARCH}/env
#ENVCOMMON+=	machines/${OSFAM}/common/env

.include <tendra.env.mk>

