# $Id: Makefile 1339 2007-07-19 00:02:32Z kate $

AR?= ar
RANLIB?= ranlib
REMOVE?= rm -f

all:
	cd error && ${MAKE} -f makefile.standalone all
	cd xalloc && ${MAKE} -f makefile.standalone all

clean:
	cd error && ${MAKE} -f makefile.standalone clean
	cd xalloc && ${MAKE} -f makefile.standalone clean
