# $TenDRA$

PDF_TITLE=	TenDRA 80x86 svr4.2 Installer Manpage
PDF_SUBJECT=	TenDRA 80x86 svr4.2 Installer Manpage

DOC?=	refentry

SRCS=	refentry.sgml

# en/manpages/trans
.include "../Makefile.inc"

# en/
.include "../../../Makefile.inc"

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
