# $TenDRA$
#
#

DOC_PREFIX?=../../../

# 80x86
SUBDIR=		80x86-cygwin32 \
		80x86-freebsd \
		80x86-linux \
		80x86-netbsd \
		80x86-openbsd \
		80x86-sco \
		80x86-solaris \
		80x86-svr4.2


# sparc
SUBDIR+=	sparc-solaris \
		sparc-sunos


# hppa
SUBDIR+=	hppa-hpux


# alpha
SUBDIR+=	alpha-freebsd \
		alpha-osf1

# power
SUBDIR+=	power-aix \
		ppc601-aix

# 680x0
SUBDIR+=	680x0-sunos

# mips
SUBDIR+=	mips-irix \
		mips-ultrix



.include "${DOC_PREFIX}/share/mk/doc.project.mk"
