# $TenDRA: Makefile 2005 2004-08-27 17:14:35Z chopra $

PDF_TITLE=	TenDRA mkerr manpage
PDF_SUBJECT=	TenDRA mkerr manpage

DOC?= refentry

SRCS=   refentry.xml

.include "../Makefile.inc"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
