--  Auto generated file. Don't edit

package body Encodings.Maps.CP_037 is

   Forward  : Forward_Map  (Character'Val( 16#4#) .. Character'Last) :=
     (Wide_Character'Val(  16#9C#),
      Wide_Character'Val(   16#9#),
      Wide_Character'Val(  16#86#),
      Wide_Character'Val(  16#7F#),
      Wide_Character'Val(  16#97#),
      Wide_Character'Val(  16#8D#),
      Wide_Character'Val(  16#8E#),
      Wide_Character'Val(   16#B#),
      Wide_Character'Val(   16#C#),
      Wide_Character'Val(   16#D#),
      Wide_Character'Val(   16#E#),
      Wide_Character'Val(   16#F#),
      Wide_Character'Val(  16#10#),
      Wide_Character'Val(  16#11#),
      Wide_Character'Val(  16#12#),
      Wide_Character'Val(  16#13#),
      Wide_Character'Val(  16#9D#),
      Wide_Character'Val(  16#85#),
      Wide_Character'Val(   16#8#),
      Wide_Character'Val(  16#87#),
      Wide_Character'Val(  16#18#),
      Wide_Character'Val(  16#19#),
      Wide_Character'Val(  16#92#),
      Wide_Character'Val(  16#8F#),
      Wide_Character'Val(  16#1C#),
      Wide_Character'Val(  16#1D#),
      Wide_Character'Val(  16#1E#),
      Wide_Character'Val(  16#1F#),
      Wide_Character'Val(  16#80#),
      Wide_Character'Val(  16#81#),
      Wide_Character'Val(  16#82#),
      Wide_Character'Val(  16#83#),
      Wide_Character'Val(  16#84#),
      Wide_Character'Val(   16#A#),
      Wide_Character'Val(  16#17#),
      Wide_Character'Val(  16#1B#),
      Wide_Character'Val(  16#88#),
      Wide_Character'Val(  16#89#),
      Wide_Character'Val(  16#8A#),
      Wide_Character'Val(  16#8B#),
      Wide_Character'Val(  16#8C#),
      Wide_Character'Val(   16#5#),
      Wide_Character'Val(   16#6#),
      Wide_Character'Val(   16#7#),
      Wide_Character'Val(  16#90#),
      Wide_Character'Val(  16#91#),
      Wide_Character'Val(  16#16#),
      Wide_Character'Val(  16#93#),
      Wide_Character'Val(  16#94#),
      Wide_Character'Val(  16#95#),
      Wide_Character'Val(  16#96#),
      Wide_Character'Val(   16#4#),
      Wide_Character'Val(  16#98#),
      Wide_Character'Val(  16#99#),
      Wide_Character'Val(  16#9A#),
      Wide_Character'Val(  16#9B#),
      Wide_Character'Val(  16#14#),
      Wide_Character'Val(  16#15#),
      Wide_Character'Val(  16#9E#),
      Wide_Character'Val(  16#1A#),
      Wide_Character'Val(  16#20#),
      Wide_Character'Val(  16#A0#),
      Wide_Character'Val(  16#E2#),
      Wide_Character'Val(  16#E4#),
      Wide_Character'Val(  16#E0#),
      Wide_Character'Val(  16#E1#),
      Wide_Character'Val(  16#E3#),
      Wide_Character'Val(  16#E5#),
      Wide_Character'Val(  16#E7#),
      Wide_Character'Val(  16#F1#),
      Wide_Character'Val(  16#A2#),
      Wide_Character'Val(  16#2E#),
      Wide_Character'Val(  16#3C#),
      Wide_Character'Val(  16#28#),
      Wide_Character'Val(  16#2B#),
      Wide_Character'Val(  16#7C#),
      Wide_Character'Val(  16#26#),
      Wide_Character'Val(  16#E9#),
      Wide_Character'Val(  16#EA#),
      Wide_Character'Val(  16#EB#),
      Wide_Character'Val(  16#E8#),
      Wide_Character'Val(  16#ED#),
      Wide_Character'Val(  16#EE#),
      Wide_Character'Val(  16#EF#),
      Wide_Character'Val(  16#EC#),
      Wide_Character'Val(  16#DF#),
      Wide_Character'Val(  16#21#),
      Wide_Character'Val(  16#24#),
      Wide_Character'Val(  16#2A#),
      Wide_Character'Val(  16#29#),
      Wide_Character'Val(  16#3B#),
      Wide_Character'Val(  16#AC#),
      Wide_Character'Val(  16#2D#),
      Wide_Character'Val(  16#2F#),
      Wide_Character'Val(  16#C2#),
      Wide_Character'Val(  16#C4#),
      Wide_Character'Val(  16#C0#),
      Wide_Character'Val(  16#C1#),
      Wide_Character'Val(  16#C3#),
      Wide_Character'Val(  16#C5#),
      Wide_Character'Val(  16#C7#),
      Wide_Character'Val(  16#D1#),
      Wide_Character'Val(  16#A6#),
      Wide_Character'Val(  16#2C#),
      Wide_Character'Val(  16#25#),
      Wide_Character'Val(  16#5F#),
      Wide_Character'Val(  16#3E#),
      Wide_Character'Val(  16#3F#),
      Wide_Character'Val(  16#F8#),
      Wide_Character'Val(  16#C9#),
      Wide_Character'Val(  16#CA#),
      Wide_Character'Val(  16#CB#),
      Wide_Character'Val(  16#C8#),
      Wide_Character'Val(  16#CD#),
      Wide_Character'Val(  16#CE#),
      Wide_Character'Val(  16#CF#),
      Wide_Character'Val(  16#CC#),
      Wide_Character'Val(  16#60#),
      Wide_Character'Val(  16#3A#),
      Wide_Character'Val(  16#23#),
      Wide_Character'Val(  16#40#),
      Wide_Character'Val(  16#27#),
      Wide_Character'Val(  16#3D#),
      Wide_Character'Val(  16#22#),
      Wide_Character'Val(  16#D8#),
      Wide_Character'Val(  16#61#),
      Wide_Character'Val(  16#62#),
      Wide_Character'Val(  16#63#),
      Wide_Character'Val(  16#64#),
      Wide_Character'Val(  16#65#),
      Wide_Character'Val(  16#66#),
      Wide_Character'Val(  16#67#),
      Wide_Character'Val(  16#68#),
      Wide_Character'Val(  16#69#),
      Wide_Character'Val(  16#AB#),
      Wide_Character'Val(  16#BB#),
      Wide_Character'Val(  16#F0#),
      Wide_Character'Val(  16#FD#),
      Wide_Character'Val(  16#FE#),
      Wide_Character'Val(  16#B1#),
      Wide_Character'Val(  16#B0#),
      Wide_Character'Val(  16#6A#),
      Wide_Character'Val(  16#6B#),
      Wide_Character'Val(  16#6C#),
      Wide_Character'Val(  16#6D#),
      Wide_Character'Val(  16#6E#),
      Wide_Character'Val(  16#6F#),
      Wide_Character'Val(  16#70#),
      Wide_Character'Val(  16#71#),
      Wide_Character'Val(  16#72#),
      Wide_Character'Val(  16#AA#),
      Wide_Character'Val(  16#BA#),
      Wide_Character'Val(  16#E6#),
      Wide_Character'Val(  16#B8#),
      Wide_Character'Val(  16#C6#),
      Wide_Character'Val(  16#A4#),
      Wide_Character'Val(  16#B5#),
      Wide_Character'Val(  16#7E#),
      Wide_Character'Val(  16#73#),
      Wide_Character'Val(  16#74#),
      Wide_Character'Val(  16#75#),
      Wide_Character'Val(  16#76#),
      Wide_Character'Val(  16#77#),
      Wide_Character'Val(  16#78#),
      Wide_Character'Val(  16#79#),
      Wide_Character'Val(  16#7A#),
      Wide_Character'Val(  16#A1#),
      Wide_Character'Val(  16#BF#),
      Wide_Character'Val(  16#D0#),
      Wide_Character'Val(  16#DD#),
      Wide_Character'Val(  16#DE#),
      Wide_Character'Val(  16#AE#),
      Wide_Character'Val(  16#5E#),
      Wide_Character'Val(  16#A3#),
      Wide_Character'Val(  16#A5#),
      Wide_Character'Val(  16#B7#),
      Wide_Character'Val(  16#A9#),
      Wide_Character'Val(  16#A7#),
      Wide_Character'Val(  16#B6#),
      Wide_Character'Val(  16#BC#),
      Wide_Character'Val(  16#BD#),
      Wide_Character'Val(  16#BE#),
      Wide_Character'Val(  16#5B#),
      Wide_Character'Val(  16#5D#),
      Wide_Character'Val(  16#AF#),
      Wide_Character'Val(  16#A8#),
      Wide_Character'Val(  16#B4#),
      Wide_Character'Val(  16#D7#),
      Wide_Character'Val(  16#7B#),
      Wide_Character'Val(  16#41#),
      Wide_Character'Val(  16#42#),
      Wide_Character'Val(  16#43#),
      Wide_Character'Val(  16#44#),
      Wide_Character'Val(  16#45#),
      Wide_Character'Val(  16#46#),
      Wide_Character'Val(  16#47#),
      Wide_Character'Val(  16#48#),
      Wide_Character'Val(  16#49#),
      Wide_Character'Val(  16#AD#),
      Wide_Character'Val(  16#F4#),
      Wide_Character'Val(  16#F6#),
      Wide_Character'Val(  16#F2#),
      Wide_Character'Val(  16#F3#),
      Wide_Character'Val(  16#F5#),
      Wide_Character'Val(  16#7D#),
      Wide_Character'Val(  16#4A#),
      Wide_Character'Val(  16#4B#),
      Wide_Character'Val(  16#4C#),
      Wide_Character'Val(  16#4D#),
      Wide_Character'Val(  16#4E#),
      Wide_Character'Val(  16#4F#),
      Wide_Character'Val(  16#50#),
      Wide_Character'Val(  16#51#),
      Wide_Character'Val(  16#52#),
      Wide_Character'Val(  16#B9#),
      Wide_Character'Val(  16#FB#),
      Wide_Character'Val(  16#FC#),
      Wide_Character'Val(  16#F9#),
      Wide_Character'Val(  16#FA#),
      Wide_Character'Val(  16#FF#),
      Wide_Character'Val(  16#5C#),
      Wide_Character'Val(  16#F7#),
      Wide_Character'Val(  16#53#),
      Wide_Character'Val(  16#54#),
      Wide_Character'Val(  16#55#),
      Wide_Character'Val(  16#56#),
      Wide_Character'Val(  16#57#),
      Wide_Character'Val(  16#58#),
      Wide_Character'Val(  16#59#),
      Wide_Character'Val(  16#5A#),
      Wide_Character'Val(  16#B2#),
      Wide_Character'Val(  16#D4#),
      Wide_Character'Val(  16#D6#),
      Wide_Character'Val(  16#D2#),
      Wide_Character'Val(  16#D3#),
      Wide_Character'Val(  16#D5#),
      Wide_Character'Val(  16#30#),
      Wide_Character'Val(  16#31#),
      Wide_Character'Val(  16#32#),
      Wide_Character'Val(  16#33#),
      Wide_Character'Val(  16#34#),
      Wide_Character'Val(  16#35#),
      Wide_Character'Val(  16#36#),
      Wide_Character'Val(  16#37#),
      Wide_Character'Val(  16#38#),
      Wide_Character'Val(  16#39#),
      Wide_Character'Val(  16#B3#),
      Wide_Character'Val(  16#DB#),
      Wide_Character'Val(  16#DC#),
      Wide_Character'Val(  16#D9#),
      Wide_Character'Val(  16#DA#),
      Wide_Character'Val(  16#9F#));

   Ranges   : Maps.Wide_Ranges  (1 ..  1) :=
     (1 => (Wide_Character'Val(   16#0#),Wide_Character'Val(  16#FF#), 1));

   Backward : Maps.Backward_Map (1 ..  256) :=
     (Character'Val( 16#0#),
      Character'Val( 16#1#),
      Character'Val( 16#2#),
      Character'Val( 16#3#),
      Character'Val(16#37#),
      Character'Val(16#2D#),
      Character'Val(16#2E#),
      Character'Val(16#2F#),
      Character'Val(16#16#),
      Character'Val( 16#5#),
      Character'Val(16#25#),
      Character'Val( 16#B#),
      Character'Val( 16#C#),
      Character'Val( 16#D#),
      Character'Val( 16#E#),
      Character'Val( 16#F#),
      Character'Val(16#10#),
      Character'Val(16#11#),
      Character'Val(16#12#),
      Character'Val(16#13#),
      Character'Val(16#3C#),
      Character'Val(16#3D#),
      Character'Val(16#32#),
      Character'Val(16#26#),
      Character'Val(16#18#),
      Character'Val(16#19#),
      Character'Val(16#3F#),
      Character'Val(16#27#),
      Character'Val(16#1C#),
      Character'Val(16#1D#),
      Character'Val(16#1E#),
      Character'Val(16#1F#),
      Character'Val(16#40#),
      Character'Val(16#5A#),
      Character'Val(16#7F#),
      Character'Val(16#7B#),
      Character'Val(16#5B#),
      Character'Val(16#6C#),
      Character'Val(16#50#),
      Character'Val(16#7D#),
      Character'Val(16#4D#),
      Character'Val(16#5D#),
      Character'Val(16#5C#),
      Character'Val(16#4E#),
      Character'Val(16#6B#),
      Character'Val(16#60#),
      Character'Val(16#4B#),
      Character'Val(16#61#),
      Character'Val(16#F0#),
      Character'Val(16#F1#),
      Character'Val(16#F2#),
      Character'Val(16#F3#),
      Character'Val(16#F4#),
      Character'Val(16#F5#),
      Character'Val(16#F6#),
      Character'Val(16#F7#),
      Character'Val(16#F8#),
      Character'Val(16#F9#),
      Character'Val(16#7A#),
      Character'Val(16#5E#),
      Character'Val(16#4C#),
      Character'Val(16#7E#),
      Character'Val(16#6E#),
      Character'Val(16#6F#),
      Character'Val(16#7C#),
      Character'Val(16#C1#),
      Character'Val(16#C2#),
      Character'Val(16#C3#),
      Character'Val(16#C4#),
      Character'Val(16#C5#),
      Character'Val(16#C6#),
      Character'Val(16#C7#),
      Character'Val(16#C8#),
      Character'Val(16#C9#),
      Character'Val(16#D1#),
      Character'Val(16#D2#),
      Character'Val(16#D3#),
      Character'Val(16#D4#),
      Character'Val(16#D5#),
      Character'Val(16#D6#),
      Character'Val(16#D7#),
      Character'Val(16#D8#),
      Character'Val(16#D9#),
      Character'Val(16#E2#),
      Character'Val(16#E3#),
      Character'Val(16#E4#),
      Character'Val(16#E5#),
      Character'Val(16#E6#),
      Character'Val(16#E7#),
      Character'Val(16#E8#),
      Character'Val(16#E9#),
      Character'Val(16#BA#),
      Character'Val(16#E0#),
      Character'Val(16#BB#),
      Character'Val(16#B0#),
      Character'Val(16#6D#),
      Character'Val(16#79#),
      Character'Val(16#81#),
      Character'Val(16#82#),
      Character'Val(16#83#),
      Character'Val(16#84#),
      Character'Val(16#85#),
      Character'Val(16#86#),
      Character'Val(16#87#),
      Character'Val(16#88#),
      Character'Val(16#89#),
      Character'Val(16#91#),
      Character'Val(16#92#),
      Character'Val(16#93#),
      Character'Val(16#94#),
      Character'Val(16#95#),
      Character'Val(16#96#),
      Character'Val(16#97#),
      Character'Val(16#98#),
      Character'Val(16#99#),
      Character'Val(16#A2#),
      Character'Val(16#A3#),
      Character'Val(16#A4#),
      Character'Val(16#A5#),
      Character'Val(16#A6#),
      Character'Val(16#A7#),
      Character'Val(16#A8#),
      Character'Val(16#A9#),
      Character'Val(16#C0#),
      Character'Val(16#4F#),
      Character'Val(16#D0#),
      Character'Val(16#A1#),
      Character'Val( 16#7#),
      Character'Val(16#20#),
      Character'Val(16#21#),
      Character'Val(16#22#),
      Character'Val(16#23#),
      Character'Val(16#24#),
      Character'Val(16#15#),
      Character'Val( 16#6#),
      Character'Val(16#17#),
      Character'Val(16#28#),
      Character'Val(16#29#),
      Character'Val(16#2A#),
      Character'Val(16#2B#),
      Character'Val(16#2C#),
      Character'Val( 16#9#),
      Character'Val( 16#A#),
      Character'Val(16#1B#),
      Character'Val(16#30#),
      Character'Val(16#31#),
      Character'Val(16#1A#),
      Character'Val(16#33#),
      Character'Val(16#34#),
      Character'Val(16#35#),
      Character'Val(16#36#),
      Character'Val( 16#8#),
      Character'Val(16#38#),
      Character'Val(16#39#),
      Character'Val(16#3A#),
      Character'Val(16#3B#),
      Character'Val( 16#4#),
      Character'Val(16#14#),
      Character'Val(16#3E#),
      Character'Val(16#FF#),
      Character'Val(16#41#),
      Character'Val(16#AA#),
      Character'Val(16#4A#),
      Character'Val(16#B1#),
      Character'Val(16#9F#),
      Character'Val(16#B2#),
      Character'Val(16#6A#),
      Character'Val(16#B5#),
      Character'Val(16#BD#),
      Character'Val(16#B4#),
      Character'Val(16#9A#),
      Character'Val(16#8A#),
      Character'Val(16#5F#),
      Character'Val(16#CA#),
      Character'Val(16#AF#),
      Character'Val(16#BC#),
      Character'Val(16#90#),
      Character'Val(16#8F#),
      Character'Val(16#EA#),
      Character'Val(16#FA#),
      Character'Val(16#BE#),
      Character'Val(16#A0#),
      Character'Val(16#B6#),
      Character'Val(16#B3#),
      Character'Val(16#9D#),
      Character'Val(16#DA#),
      Character'Val(16#9B#),
      Character'Val(16#8B#),
      Character'Val(16#B7#),
      Character'Val(16#B8#),
      Character'Val(16#B9#),
      Character'Val(16#AB#),
      Character'Val(16#64#),
      Character'Val(16#65#),
      Character'Val(16#62#),
      Character'Val(16#66#),
      Character'Val(16#63#),
      Character'Val(16#67#),
      Character'Val(16#9E#),
      Character'Val(16#68#),
      Character'Val(16#74#),
      Character'Val(16#71#),
      Character'Val(16#72#),
      Character'Val(16#73#),
      Character'Val(16#78#),
      Character'Val(16#75#),
      Character'Val(16#76#),
      Character'Val(16#77#),
      Character'Val(16#AC#),
      Character'Val(16#69#),
      Character'Val(16#ED#),
      Character'Val(16#EE#),
      Character'Val(16#EB#),
      Character'Val(16#EF#),
      Character'Val(16#EC#),
      Character'Val(16#BF#),
      Character'Val(16#80#),
      Character'Val(16#FD#),
      Character'Val(16#FE#),
      Character'Val(16#FB#),
      Character'Val(16#FC#),
      Character'Val(16#AD#),
      Character'Val(16#AE#),
      Character'Val(16#59#),
      Character'Val(16#44#),
      Character'Val(16#45#),
      Character'Val(16#42#),
      Character'Val(16#46#),
      Character'Val(16#43#),
      Character'Val(16#47#),
      Character'Val(16#9C#),
      Character'Val(16#48#),
      Character'Val(16#54#),
      Character'Val(16#51#),
      Character'Val(16#52#),
      Character'Val(16#53#),
      Character'Val(16#58#),
      Character'Val(16#55#),
      Character'Val(16#56#),
      Character'Val(16#57#),
      Character'Val(16#8C#),
      Character'Val(16#49#),
      Character'Val(16#CD#),
      Character'Val(16#CE#),
      Character'Val(16#CB#),
      Character'Val(16#CF#),
      Character'Val(16#CC#),
      Character'Val(16#E1#),
      Character'Val(16#70#),
      Character'Val(16#DD#),
      Character'Val(16#DE#),
      Character'Val(16#DB#),
      Character'Val(16#DC#),
      Character'Val(16#8D#),
      Character'Val(16#8E#),
      Character'Val(16#DF#));

   function Decode (Char : Character) return Wide_Character is
   begin
      return Decode (Char, Forward);
   end Decode;

   procedure Decode
     (Text        : in     Raw_String;
      Text_Last   :    out Natural;
      Result      :    out Wide_String;
      Result_Last :    out Natural;
      Map         : in     Encoding := Encodings.CP_037)
   is
   begin
      Decode (Text, Text_Last, Result, Result_Last, Forward);
   end Decode;

   procedure Encode
     (Text        : in     Wide_String;
      Text_Last   :    out Natural;
      Result      :    out Raw_String;
      Result_Last :    out Natural;
      Map         : in     Encoding := Encodings.CP_037)
   is
   begin
      Encode (Text, Text_Last, Result, Result_Last,
              Ranges, Backward);
   end Encode;

begin
   Encoder_List (Encodings.CP_037) := Encode'Access;
   Decoder_List (Encodings.CP_037) := Decode'Access;
end Encodings.Maps.CP_037;
