# $TenDRA$

PROG=	trans

# installers/mips/ultrix
SRCS=	main.c out_ba.c

# installers/mips
.include "${.CURDIR}/../Makefile.inc"

# installers/
.include "${.CURDIR}/../../Makefile.inc"

.include "${.CURDIR}/../../../../mk/base/tendra.prog.mk"
