# $Id$

.include "Makefile.inc"


MACHTOK_DEP   	= dep_toks.tpl
MACHTOK_MAP   	= map_toks.tpl
MACHTOK_EXCEPT	= except_toks.tpl
MACHTOK_MODEL 	= lp64.tpl
MACHTOK_FLOAT 	= ieee754-double.tpl

.include <tendra.machtok.mk>

