# $Id$

.include "Makefile.inc"

.include <tendra.base.mk>
.include <tendra.makedefs.mk>


MACHTOK_DEP   	= dep_toks.tpl
MACHTOK_MAP   	= map_toks.tpl
MACHTOK_EXCEPT	= ${BLDARCH}-be.tpl
MACHTOK_MODEL 	= ilp32.tpl
MACHTOK_FLOAT 	= ieee754-double.tpl

.include <tendra.machtok.mk>

