# $TenDRA$

PREFIX?=	@PREFIX@
TMP_DIR?=	@TMP_DIR@
MACH_OS=	@MACH_OS@
MACH_VERS=	@MACH_VERS@
MACH_CPU=	@MACH_CPU@
MACH_EXEC=	@MACH_EXEC@
MACH_DIR=	${PREFIX}/lib/TenDRA/machines
MACH_BASE=	${MACH_DIR}/${MACH_OS}/${MACH_VERS}/${MACH_CPU}
INSTALL_DIR=	${PREFIX}/lib/TenDRA
COMMON_DIR=	${INSTALL_DIR}/lib


OBJ_PREFIX=	@OBJ_PREFIX@

MAN_COMPRESS=	@MAN_COMPRESS@
MAN_INSTALL=	@MAN_INSTALL@

# DON'T CHANGE ANYTHING BELOW THIS LINE UNLESS YOU KNOW WHAT YOU ARE DOING

SRC_DIR=	@SRC_DIR@
SRC_ENV=	@SRC_ENV@
SRC_MACHINES=	@SRC_MACHINES@

BUILD_OS=	@BUILD_OS@
OBJ_ENV=	${OBJ_PREFIX}/@OBJ_ENV@
DEFAULT_BUILD=	${OBJ_ENV}/${SRC_ENV}/default-build

.include "${SRC_DIR}/mk/def/def.@MACH_OS_LCASE@.mk"

.if exists (${SRC_DIR}/mk/config/config.@MACH_OS_LCASE@.@MACH_CPU@.mk)
.include "${SRC_DIR}/mk/config/config.@MACH_OS_LCASE@.@MACH_CPU@.mk"
.endif
