# $Id$

.include "Makefile.inc"


CCOPTS+=	-I ..
CCOPTS+=	-I .

SRCS+=	dw2_abbrev.c
SRCS+=	dw2_basic.c
SRCS+=	dw2_common.c
SRCS+=	dw2_entries.c
SRCS+=	dw2_iface.c
SRCS+=	dw2_info.c
SRCS+=	dw2_lines.c
SRCS+=	dw2_locdata.c
SRCS+=	dw2_types.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

