# $TenDRA$

.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

.PATH :	${.CURDIR}/images

IMAGES_OBJ?=	calc.obj

DOC?= book

SRCS=   book.sgml

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
