# $TenDRA$

.PATH :	${.CURDIR}/images

PDF_TITLE=	calculus User's Guide
PDF_SUBJECT=	calculus User's Guide

IMAGES_OBJ?=	calc.obj

DOC?= book

SRCS=   book.xml


.include "../Makefile.inc"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
