/*
    		 Crown Copyright (c) 1997
    
    This TenDRA(r) Computer Program is subject to Copyright
    owned by the United Kingdom Secretary of State for Defence
    acting through the Defence Evaluation and Research Agency
    (DERA).  It is made available to Recipients with a
    royalty-free licence for its use, reproduction, transfer
    to other parties and amendment for any purpose not excluding
    product development provided that any such use et cetera
    shall be deemed to be acceptance of the following conditions:-
    
        (1) Its Recipients shall ensure that this Notice is
        reproduced upon any copies or amended versions of it;
    
        (2) Any amended version of it shall be clearly marked to
        show both the nature of and the organisation responsible
        for the relevant amendment or amendments;
    
        (3) Its onward transfer from a recipient to another
        party shall be deemed to be that party's acceptance of
        these conditions;
    
        (4) DERA gives no warranty or assurance as to its
        quality or suitability for any purpose and DERA accepts
        no liability whatsoever in relation to any use to which
        it may be put.
*/


@use bytestream
@use tokdec_props
@use tokdef_props
@use tagdec_props
@use tagdef_props
@use al_tagdef_props
@use version_props
@special external
@special token
@special tokdec
@special tokdef
@special tagdec
@special tagdef
@special al_tagdef
@special version
@special token_defn
@special sortname
#ifndef TDF_INCLUDED
#define TDF_INCLUDED


/* AUTOMATICALLY GENERATED BY %ZX VERSION %ZV FROM TDF %VA.%VB */

extern void init_constructs PROTO_S ( ( void ) ) ;
extern sortname find_sort PROTO_S ( ( char ) ) ;

@loop sort
@if sort.basic
@if sort.special
extern long de_%SN_bits PROTO_S ( ( void ) ) ;
@else
extern node *de_%SN PROTO_S ( ( void ) ) ;
@endif
@endif
@end

#ifdef ENC_TYPES_INCLUDED
@loop sort
@if sort.basic
@if sort.special
extern void enc_%SN_bits PROTO_S ( ( bitstream *, int ) ) ;
@else
@if sort.edge
extern void enc_%SN_bits PROTO_S ( ( bitstream *, int ) ) ;
@endif
@endif
@endif
@end
#endif

@loop sort
@if sort.basic
@if !sort.special
extern node *read_%SN PROTO_S ( ( long ) ) ;
@endif
@endif
@end

#define VERSION_capsule		%48t"TDFC"
#define VERSION_library		%48t"TDFL"
#define VERSION_major		%48t%VA
#define VERSION_minor		%48t%VB

@loop sort
@if sort.unit
#define LINK_%SN		%48t"%SU"
@endif
@end
#define LINK_tld_props		%48t"tld"

@loop sort
@if sort.link
#define LINK_%SN		%48t"%SL"
@endif
@end

@special !sortname
@loop sort
@if sort.eq.sortname
@loop sort.cons
@if cons.eq.alignment_sort
#define SORT_alignment		%48t%CE
@else
#define SORT_%CN		%48t%CE
@endif
@end
#define SORT_foreign		%48tENC_foreign_sort
#define SORT_callees		%48t%1SM
#define SORT_error_code		%48t%2SM
#define SORT_sortname		%48t0
#define SORT_unknown		%48t%u
#define SORT_repeat		%48t( -%u )
#define SORT_option		%48t( -%u )
#define SORT_completion		%48t( -%u )
#define SORT_small_tdfint	%48t( -%u )
@loop sort
@if sort.builtin
#define SORT_%SN		%48t( -%u )
@endif
@end
#define SORT_max		%48t%SM
#define SORT_no			%48t%3SM
@endif
@end

@loop sort
@if sort.basic
@loop sort.cons
#define ENC_%27CN	%48t%CE
@end
@if sort.eq.shape
#define ENC_shape_none	%48t%1SM
@endif
@endif
@end


#endif
