# $Id$

.include "Makefile.inc"


TSPEC=  ${OBJ_DIR}/src/tspec

TSPEC_FLAGS+=   -a
TSPEC_FLAGS+=	-I${BASE_DIR}/extension

APIS+=	bsd_extn
APIS+=	gcc
APIS+=	cpp
#APIS+=	motif/1_2
#APIS+=	x5/aw
#APIS+=	x5
#APIS+=	x5/lib
#APIS+=	x5/mit
#APIS+=	x5/mu
#APIS+=	x5/proto
#APIS+=	x5/t

APIS+=	cae/dtp-xa
APIS+=	cae/acse-xap
APIS+=	cae/xns5-socket
APIS+=	cae/xns5-ar

APIS+=	sus/xsh2

.include <tendra.tspec.mk>

