# $TenDRA$

.PATH : ${.CURDIR} ${.CURDIR}/../../../common

DATA=	Xa Xc Xp Xs Xt Xw default.extra tcc_diag tcc_prof

INSTALL_ENV=	yes

# This lives in env/, and sucks in the env/common files.
.include "../../../Makefile.inc"

.include "../../../../../../mk/base/tendra.prog.mk"
