# $Id: Makefile 1468 2007-09-15 23:54:20Z kate $

.include "Makefile.inc"


CCOPTS+=	-I${.CURDIR}/../shared/error
CCOPTS+=	-I${.CURDIR}/../shared/xalloc

SRCS+=	calculus.c

.include <tendra.obj.mk>

.include <tendra.partial.mk>

