# $TenDRA$

PROG=	trans

# installers/alpha/freebsd
SRCS=	driver.c

# installers/alpha
.include "${.CURDIR}/../Makefile.inc"

# installers/
.include "${.CURDIR}/../../Makefile.inc"

.include "${.CURDIR}/../../../../mk/base/tendra.prog.mk"
