# $Id$

NAME=specification
SOURCE=specification.xml
PROJECT_NAME=specification
PROJECT_URL=http://docs.tendra.org/
RESOURCES=../style/docbook.css ../style/common.css images/*.gif
CSSFILE=docbook.css
XHTMLSTYLE=../xsl/tendra-docbook-chunked.xsl
XHTMLSTYLE_SINGLE=../xsl/tendra-docbook-single.xsl

include ../doctools/Mk/docbook.mk
