/*
    			 Crown Copyright (c) 1997
    
    This TenDRA(r) Computer Program is subject to Copyright
    owned by the United Kingdom Secretary of State for Defence
    acting through the Defence Evaluation and Research Agency
    (DERA).  It is made available to Recipients with a
    royalty-free licence for its use, reproduction, transfer
    to other parties and amendment for any purpose not excluding
    product development provided that any such use et cetera
    shall be deemed to be acceptance of the following conditions:-
    
        (1) Its Recipients shall ensure that this Notice is
        reproduced upon any copies or amended versions of it;
    
        (2) Any amended version of it shall be clearly marked to
        show both the nature of and the organisation responsible
        for the relevant amendment or amendments;
    
        (3) Its onward transfer from a recipient to another
        party shall be deemed to be that party's acceptance of
        these conditions;
    
        (4) DERA gives no warranty or assurance as to its
        quality or suitability for any purpose and DERA accepts
        no liability whatsoever in relation to any use to which
        it may be put.
*/


@use all
@special external
@special sortname
@special token
@special tokdec
@special tokdef
@special tagdec
@special tagdef
@special al_tagdef
@special diag_tagdef
@special token_defn
@special exp case
@special exp labelled
@special exp make_proc
@special nat make_nat
@special signed_nat make_signed_nat
@special string make_string
@special version make_version
#ifndef TDF_INCLUDED
#define TDF_INCLUDED


/* AUTOMATICALLY GENERATED BY %ZX VERSION %ZV FROM TDF %VA.%VB */

@loop sort
@if sort.basic
extern long de_%SN PROTO_S ( ( void ) ) ;
@endif
@end

extern void decode PROTO_S ( ( char * ) ) ;
extern sortid find_sort PROTO_S ( ( sortname ) ) ;
extern sortname find_sortname PROTO_S ( ( int ) ) ;
extern void init_foreign_sorts PROTO_S ( ( void ) ) ;
extern char find_variable PROTO_S ( ( string, long ) ) ;
typedef void ( *equation_func ) PROTO_S ( ( void ) ) ;
extern equation_func find_equation PROTO_S ( ( string, string *, int * ) ) ;

@loop sort
@if sort.link
extern long var_%SN ;
@endif
@end

#define version_magic		%48t"TDFC"
#define version_major		%48t%VA
#define version_minor		%48t%VB

@loop sort
@if sort.unit
#define HAVE_%SN		%48t1
@endif
@end

@loop sort
@if sort.basic
#define sort_%20SN		%48t%SCE
@endif
@end
#define sort_foreign		%48tsortname_foreign_sort
#define sort_unknown		%48t0

@loop sort
@loop sort.cons
@if sort.special
#define %10SN_%20CN		%48t%CE
@else
@if cons.special
#define %10SN_%20CN		%48t%CE
@if cons.eq.make_string
#define %10SN_bits		%48t%SB
#define %10SN_ext		%48t%SE
@endif
@endif
@endif
@end
@end


#endif
